tencentcloudstack/terraform-provider-tencentcloud

examples/tencentcloud-subnet/main.tf, website/docs/d/mysql_backup_list.html.markdown, website/docs/d/mysql_instance.html.markdown, website/docs/d/mysql_parameter_list.html.markdown, website/docs/d/mysql_zone_config.html.markdown, website/docs/r/mysql_account.html.markdown, website/docs/r/mysql_account_privilege.html.markdown, website/docs/r/mysql_backup_policy.html.markdown, website/docs/r/mysql_instance.html.markdown, website/docs/r/mysql_readonly_instance.html.markdown, website/docs/r/security_group.html.markdown, website/docs/r/subnet.html.markdown, website/tencentcloud.erb
1.optimize document description.
2.add test example for vpc route tabe.
=> optimize document description and add test example for vpc route tabe.

tencentcloud/resource_tc_route_table.go
Need to determine that the array is empty
#34
=> Need to determine that the array is empty

tencentcloud/resource_tc_route_table.go, tencentcloud/resource_tc_security_group.go
Revert to the old code[security_group],  api has change compatibility.
=>  Revert to the old code[security_group],  api has change compatibility.

tencentcloud/resource_tc_eip.go, tencentcloud/resource_tc_eip_association.go, tencentcloud/service_tencentcloud_dc.go
```
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudEipAssociation -timeout 120m
?       github.com/terraform-providers/terraform-provider-tencentcloud/gendoc   [no test files]
=== RUN   TestAccTencentCloudEipAssociationWithInstance
--- PASS: TestAccTencentCloudEipAssociationWithInstance (30.37s)
=== RUN   TestAccTencentCloudEipAssociationWithNetworkInterface
--- PASS: TestAccTencentCloudEipAssociationWithNetworkInterface (10.74s)
PASS
ok      github.com/terraform-providers/terraform-provider-tencentcloud/tencentcloud     41.125s
?       github.com/terraform-providers/terraform-provider-tencentcloud/tencentcloud/connectivity        [no test …
```
=> checking eip bind status after binding #67

tencentcloud/resource_tc_security_group_rule.go, tencentcloud/resource_tc_security_group_rule_test.go, tencentcloud/service_tencentcloud_vpc.go
Rollback to old security_group_rule ID generation
=> Fix security_group_rule buildID

CHANGELOG.md, tencentcloud/resource_tc_instance.go, tencentcloud/resource_tc_instance_test.go, website/docs/r/instance.html.markdown
The `tencentcloud_instance.image_id` property becomes ForceNew.
#78
=> The `tencentcloud_instance.image_id` property becomes ForceNew.

examples/tencentcloud-clb/main.tf, tencentcloud/data_source_tc_clb_attachments.go, tencentcloud/data_source_tc_clb_listener_rules.go, tencentcloud/data_source_tc_clb_listeners.go, tencentcloud/data_source_tc_clb_redirections.go, tencentcloud/resource_tc_clb_attachment.go, tencentcloud/resource_tc_clb_instance.go, tencentcloud/resource_tc_clb_listener.go, tencentcloud/resource_tc_clb_listener_rule.go, tencentcloud/resource_tc_clb_listener_rule_test.go, tencentcloud/resource_tc_clb_listener_test.go, tencentcloud/resource_tc_clb_redirection.go, tencentcloud/service_tencentcloud_clb.go, website/docs/d/clb_attachments.html.markdown, website/docs/d/clb_listener_rules.html.markdown, website/docs/d/clb_listeners.html.markdown, website/docs/d/clb_redirections.html.markdown, website/docs/r/clb_attachment.html.markdown, website/docs/r/clb_instance.html.markdown, website/docs/r/clb_listener.html.markdown, website/docs/r/clb_listener_rule.html.markdown, website/docs/r/clb_redirection.html.markdown
get elegant way of id creation
=> get elegant way of id creation

examples/tencentcloud-clb/main.tf, tencentcloud/data_source_tc_clb_attachments.go, tencentcloud/data_source_tc_clb_attachments_test.go, tencentcloud/data_source_tc_clb_instances.go, tencentcloud/data_source_tc_clb_listener_rules.go, tencentcloud/data_source_tc_clb_listener_rules_test.go, tencentcloud/data_source_tc_clb_listeners.go, tencentcloud/data_source_tc_clb_redirections.go, tencentcloud/data_source_tc_clb_redirections_test.go, tencentcloud/resource_tc_clb_attachment.go, tencentcloud/resource_tc_clb_instance.go, tencentcloud/resource_tc_clb_listener.go, tencentcloud/resource_tc_clb_listener_rule.go, tencentcloud/resource_tc_clb_redirection.go, tencentcloud/resource_tc_clb_redirection_test.go, tencentcloud/service_tencentcloud_clb.go, website/docs/d/clb_attachments.html.markdown, website/docs/d/clb_instances.html.markdown, website/docs/d/clb_listener_rules.html.markdown, website/docs/d/clb_listeners.html.markdown, website/docs/d/clb_redirections.html.markdown, website/docs/r/clb_attachment.html.markdown, website/docs/r/clb_instance.html.markdown, website/docs/r/clb_listener.html.markdown, website/docs/r/clb_listener_rule.html.markdown, website/docs/r/clb_redirection.html.markdown
rename listener_rule_id as rule_id
=> rename listener_rule_id as rule_id

website/docs/r/instance.html.markdown
updated the document to fix issue # 116. The original document looks like as if this parameter is a boolean value.
=> fix issue #116

website/docs/r/instance.html.markdown
=> Add limitations to tag key name.

CHANGELOG.md, GNUmakefile, tencentcloud/resource_tc_mysql_backup_policy.go, tencentcloud/resource_tc_mysql_backup_policy_test.go, tencentcloud/service_tencentcloud_mysql.go, website/docs/r/mysql_backup_policy.html.markdown
- `tencentcloud_mysql_backup_policy`: `backup_model` remove logical backup support. 
- `tencentcloud_mysql_instance`: `tags` adapt to the new official api.
=> problem handling caused by  mysql API update.

CHANGELOG.md, tencentcloud/resource_tc_kubernetes_cluster.go, tencentcloud/resource_tc_kubernetes_scale_worker.go
* Resource: `tencentcloud_kubernetes_cluster`: cgi error retry.
* Resource: `tencentcloud_kubernetes_scale_worker`: cgi error retry.
=> kubernetes cgi error retry.

CHANGELOG.md, tencentcloud/extension_clb.go, tencentcloud/resource_tc_clb_redirection.go, tencentcloud/resource_tc_clb_redirection_test.go, website/docs/d/clb_redirections.html.markdown, website/docs/r/clb_redirection.html.markdown
add auto redirection in resouce redirection
=> add auto redirection in resouce redirection

CHANGELOG.md, tencentcloud/extension_mysql.go, tencentcloud/resource_tc_mysql_instance.go
BUG FIXIES:
* Resource: `tencentcloud_mysql_instance`: when the mysql is abnormal state, read the basic information report error
=> bug fix:when the mysql is abnormal state, read the basic information  report error

CHANGELOG.md, examples/tencentcloud-as/main.tf, tencentcloud/data_source_tc_as_scaling_groups.go, tencentcloud/data_source_tc_as_scaling_groups_test.go, tencentcloud/resource_tc_as_scaling_group.go, tencentcloud/resource_tc_as_scaling_group_test.go, tencentcloud/service_tencentcloud_as.go, website/docs/d/as_scaling_groups.html.markdown, website/docs/r/as_scaling_group.html.markdown
- `as_scaling_group` now can set and modify tags
- `as_scaling_groups` now can use tags to filter
=> Add as scaling group tags support

CHANGELOG.md, go.mod, go.sum, tencentcloud/data_source_tc_reserved_instance_configs.go, tencentcloud/data_source_tc_reserved_instance_configs_test.go, tencentcloud/data_source_tc_reserved_instances.go, tencentcloud/data_source_tc_reserved_instances_test.go, tencentcloud/provider.go, tencentcloud/resource_tc_reserved_instance.go, tencentcloud/service_tencentcloud_cvm.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/as/v20180419/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cbs/v20170312/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cbs/v20170312/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdb/v20170320/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdb/v20170320/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/clb/v20180317/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile/http_profile.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm/v20170312/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm/v20170312/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/gaap/v20180529/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/gaap/v20180529/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tag/v20180813/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/models.go, vendor/modules.txt, website/docs/d/reserved_instance_configs.html.markdown, website/docs/d/reserved_instances.html.markdown, website/docs/r/reserved_instance.html.markdown, website/tencentcloud.erb
* **New Data Source**: `tencentcloud_reserved_instance_configs`
* **New Data Source**: `tencentcloud_reserved_instances`
* **New Resource**: `tencentcloud_reserved_instance`
=> support reserved instance

gendoc/main.go, go.sum
add `result_output_file` check for data source, but skip for deprecated data source
=> feat(gendoc): add result_output_file check for data source

CHANGELOG.md, tencentcloud/resource_tc_kubernetes_cluster.go, tencentcloud/resource_tc_kubernetes_scale_worker.go
* Resource: `tencentcloud_kubernetes_cluster` add error handling logic.
* Resource: `tencentcloud_kubernetes_scale_worker` add error handling logic.
=> Add errors handling logic for tke

tencentcloud/resource_tc_kubernetes_cluster.go, website/docs/r/kubernetes_cluster.html.markdown, website/docs/r/kubernetes_scale_worker.html.markdown
modify cvm  parameters for tke logic.
=> modify cvm  parameters for tke logic.

tencentcloud/resource_tc_vpn_connection.go, website/docs/r/vpn_connection.html.markdown
fix large integer issue when building on 32-bit platform
=> fix large integer issue when building on 32-bit platform

tencentcloud/resource_tc_key_pair.go
=> Fix key pair destroy

tencentcloud/resource_tc_cam_group.go, tencentcloud/resource_tc_cam_group_membership.go, tencentcloud/resource_tc_cam_group_policy_attachment.go, tencentcloud/resource_tc_cam_policy.go, tencentcloud/resource_tc_cam_role.go, tencentcloud/resource_tc_cam_role_policy_attachment.go, tencentcloud/resource_tc_cam_saml_provider.go, tencentcloud/resource_tc_cam_user.go, tencentcloud/resource_tc_cam_user_policy_attachment.go, website/docs/d/cam_group_policy_attachments.html.markdown, website/docs/d/cam_user_policy_attachments.html.markdown
fix null response when create request finished and pull get request in a very short time on resource CAM POLICY
=> fix type error issue

tencentcloud/resource_tc_cam_saml_provider.go, website/docs/r/cam_saml_provider.html.markdown
=> add force new mark

tencentcloud/data_source_tc_nat_gateways.go
fix type error in data `tencentcloud_nat_gateways`
=> fix type error

tencentcloud/data_source_tc_nat_gateways_test.go, tencentcloud/resource_tc_kubernetes_cluster.go
1.fix error test case in data source `tencentcloud_nat_gateways`
2.fix bug in resource `kubernetes_cluster`
=> fix error test case

tencentcloud/resource_tc_nat_gateway.go, website/docs/r/nat_gateway.html.markdown
fix error of `assigned_eip_set` of resource `tencentcloud_nat_gateway`
=> fix error of `assigned_eip_set` of resource `tencentcloud_nat_gateway`

tencentcloud/resource_tc_tcaplus_idl.go, tencentcloud/resource_tc_tcaplus_table.go, website/docs/r/tcaplus_idl.html.markdown, website/docs/r/tcaplus_table.html.markdown
=> idl not need `zone_id`

tencentcloud/service_tencentcloud_cam.go
add additional error code to fix bugs
=> add additional error code to fix bugs

tencentcloud/provider.go, website/tencentcloud.erb
Adjust the order of tcaplus documents
=> Adjust the order of tcaplus documents

tencentcloud/service_tencentcloud_tcaplus.go
tcaplus need urlencode & base64encode idl content.
=> FileContent  urlencode +base64encode

tencentcloud/resource_tc_tcaplus_application.go
#276 
retry create   tcaplus error code  ResourceUnavailable
=> retry create   tcaplus error code  ResourceUnavailable

CHANGELOG.md, tencentcloud/service_tencentcloud_redis.go
Resource: `tencentcloud_redis_instance` field security_groups are id list,not name list
=> `tencentcloud_redis_instance` field security_groups are id list,not name list

tencentcloud/data_source_tc_mysql_instance_test.go
=> name and size change

CHANGELOG.md, tencentcloud/service_tencentcloud_vpc.go
> === RUN   TestAccTencentCloudEniAttachmentBasic
> --- PASS: TestAccTencentCloudEniAttachmentBasic (47.11s)
> PASS
> ok      github.com/terraform-providers/terraform-provider-tencentcloud/tencentcloud     47.145s
=> fix detach may cause error

tencentcloud/resource_tc_dayu_ddos_policy_attachment_test.go, tencentcloud/resource_tc_eip_association_test.go, tencentcloud/service_tencentcloud_mysql.go
=> err solute.

tencentcloud/data_source_tc_clb_instances.go, tencentcloud/resource_tc_alb_server_attachment.go, tencentcloud/resource_tc_eip.go, tencentcloud/resource_tc_ha_vip_eip_attachment.go, tencentcloud/resource_tc_security_group_rule.go, tencentcloud/resource_tc_tcaplus_table.go, tencentcloud/service_tencentcloud_clb.go, tencentcloud/service_tencentcloud_dayu.go, tencentcloud/service_tencentcloud_mysql.go, tencentcloud/service_tencentcloud_tke.go
solute some unhandled errors and some missing codes.
#322
=> solute some unhandled errors and some missing codes.

examples/tencentcloud-vpn/main.tf, tencentcloud/basic_test.go, tencentcloud/data_source_tc_scf_functions.go, tencentcloud/data_source_tc_scf_functions_test.go, tencentcloud/data_source_tc_scf_namespaces.go, tencentcloud/resource_tc_scf_function.go, tencentcloud/resource_tc_scf_function_test.go, tencentcloud/service_tencentcloud_scf.go, website/docs/d/scf_namespaces.html.markdown
fix:
data source scf function may panic with nil pointer
data source scf
namespace doc example
optimize:
resource scf function
=> fix: fix scf data source panic

tencentcloud/data_source_tc_mysql_instance.go, tencentcloud/extension_redis.go, tencentcloud/internal/helper/transform.go, tencentcloud/resource_tc_as_scaling_group.go, tencentcloud/resource_tc_clb_listener.go, tencentcloud/resource_tc_clb_listener_rule.go, tencentcloud/resource_tc_eni_attachment_test.go, tencentcloud/resource_tc_kubernetes_cluster.go, tencentcloud/resource_tc_kubernetes_scale_worker_test.go, tencentcloud/resource_tc_redis_instance.go, tencentcloud/resource_tc_route_table_entry.go, tencentcloud/service_tencentcloud_redis.go, website/docs/d/mysql_instance.html.markdown, website/docs/r/as_scaling_group.html.markdown
=== RUN   TestAccTencentCloudRedisInstancesDataSource
preemptall
preemptall
--- PASS: TestAccTencentCloudRedisInstancesDataSource (41.36s)
=== RUN   TestAccDataSourceRedisZoneConfig_basic
--- PASS: TestAccDataSourceRedisZoneConfig_basic (1.31s)
=== RUN   TestAccTencentCloudRedisBackupConfig
--- PASS: TestAccTencentCloudRedisBackupConfig (47.71s)
=== RUN   TestAccTencentCloudRedisInstance
--- PASS: TestAccTencentCloudRedisInstance (61.40s)
PASS
ok      github.com/terraform-providers/terraform-provider-tencentcloud/tencentcloud     154.950s
=> pull redis available zone  from the interface of CVM

CHANGELOG.md, tencentcloud/resource_tc_dayu_cc_https_policy.go, tencentcloud/resource_tc_dayu_ddos_policy.go, tencentcloud/resource_tc_dayu_ddos_policy_attachment.go, tencentcloud/resource_tc_dayu_ddos_policy_case.go, tencentcloud/resource_tc_dayu_l4_rule.go, tencentcloud/resource_tc_dayu_l7_rule.go, tencentcloud/resource_tc_dnat.go, tencentcloud/resource_tc_vpn_gateway.go, website/docs/r/dayu_ddos_policy.html.markdown
resource `vpn_gateway` `state` type error
resource `dayu_cc_https_policy` message description error
resource `dayu_ddos_policy` unchangable white_ips and black_ips
resource `dayu_l4_rule` unchangable rule paras
resource `dayu_l7_rule` `dayu_l4_rule` add InternalError process
resource `dayu_ddos_policy` error description of `end_port`
=> fix bugs that resource `dnat` `elastic_port` `internal_port` type error;

CHANGELOG.md, tencentcloud/extension_tke.go, tencentcloud/resource_tc_kubernetes_cluster.go, tencentcloud/resource_tc_kubernetes_cluster_test.go, tencentcloud/service_tencentcloud_tke.go, website/docs/r/kubernetes_cluster.html.markdown
* Resource: `tencentcloud_kubernetes_cluster` add new attributes ,`cluster_internet`,`cluster_intranet`,`managed_cluster_internet_security_policies` and `cluster_intranet_subnet_id`.
#335
=> Add  internet and intranet support for kubernetes .

CHANGELOG.md, examples/tencentcloud-cam/main.tf, tencentcloud/data_source_tc_cam_group_memberships_test.go, tencentcloud/data_source_tc_cam_user_policy_attachments_test.go, tencentcloud/data_source_tc_cam_users_test.go, tencentcloud/resource_tc_cam_group.go, tencentcloud/resource_tc_cam_group_membership.go, tencentcloud/resource_tc_cam_group_membership_test.go, tencentcloud/resource_tc_cam_group_policy_attachment.go, tencentcloud/resource_tc_cam_policy.go, tencentcloud/resource_tc_cam_role.go, tencentcloud/resource_tc_cam_role_policy_attachment.go, tencentcloud/resource_tc_cam_saml_provider.go, tencentcloud/resource_tc_cam_user.go, tencentcloud/resource_tc_cam_user_policy_attachment.go, tencentcloud/resource_tc_cam_user_policy_attachment_test.go, tencentcloud/resource_tc_cam_user_test.go, website/docs/r/cam_user.html.markdown
enchance the create and read process
=> add new atrribute `delete_force` of resource `tencentcloud_cam_user`

tencentcloud/resource_tc_cam_group.go, tencentcloud/resource_tc_cam_policy.go, tencentcloud/resource_tc_cam_role.go, tencentcloud/resource_tc_cam_saml_provider.go, tencentcloud/resource_tc_cam_user.go
=> add create nonretryable error

tencentcloud/resource_tc_cam_group.go, tencentcloud/resource_tc_cam_group_membership.go, tencentcloud/resource_tc_cam_group_policy_attachment.go, tencentcloud/resource_tc_cam_group_test.go, tencentcloud/resource_tc_cam_policy.go, tencentcloud/resource_tc_cam_role.go, tencentcloud/resource_tc_cam_role_policy_attachment.go, tencentcloud/resource_tc_cam_saml_provider.go, tencentcloud/resource_tc_cam_user.go, tencentcloud/resource_tc_cam_user_policy_attachment.go
=> optimize the api style

examples/tencentcloud-tcaplus/main.tf, tencentcloud/resource_tc_tcaplus_idl.go, tencentcloud/resource_tc_tcaplus_table.go, website/docs/r/tcaplus_idl.html.markdown, website/docs/r/tcaplus_table.html.markdown
Fill in the missing parameter `zone_id`
=> Fill in the missing parameter `zone_id`

tencentcloud/resource_tc_cam_group.go, tencentcloud/resource_tc_cam_group_membership.go, tencentcloud/resource_tc_cam_group_policy_attachment.go, tencentcloud/resource_tc_cam_policy.go, tencentcloud/resource_tc_cam_role.go, tencentcloud/resource_tc_cam_role_policy_attachment.go, tencentcloud/resource_tc_cam_saml_provider.go, tencentcloud/resource_tc_cam_user.go, tencentcloud/resource_tc_cam_user_policy_attachment.go, tencentcloud/service_tencentcloud_vpc.go
and add more time wait for CAM resources creation
=> add retry process to resource `tencentcloud_vpc` 

tencentcloud/data_source_tc_cam_users.go, tencentcloud/data_source_tc_cam_users_test.go, tencentcloud/resource_tc_cam_user.go, website/docs/d/cam_users.html.markdown
=> fix crash issue

CHANGELOG.md, tencentcloud/extension_cvm.go, tencentcloud/resource_tc_key_pair.go
=> Fix bug when trying to destroy resources containing CVM and key pair

CHANGELOG.md, tencentcloud/resource_tc_cdn_domain.go, website/docs/r/cdn_domain.html.markdown
=> cdn domain add argument cname

CHANGELOG.md, tencentcloud/provider.go, tencentcloud/resource_tc_instance.go, tencentcloud/resource_tc_kubernetes_cluster_attachment.go, tencentcloud/resource_tc_kubernetes_cluster_attachment_test.go, tencentcloud/service_tencentcloud_tke.go, website/docs/r/kubernetes_cluster_attachment.html.markdown, website/tencentcloud.erb
**New Resource**: `tencentcloud_kubernetes_cluster_attachment`
=== RUN   TestAccTencentCloudTkeAttachResource
--- PASS: TestAccTencentCloudTkeAttachResource (390.07s)
PASS
ok      github.com/terraform-providers/terraform-provider-tencentcloud/tencentcloud     390.562s
=> tke attachment resource

tencentcloud/data_source_tc_tcaplus_applications.go, tencentcloud/resource_tc_ccn_attachment.go, tencentcloud/service_tencentcloud_ccn.go, website/docs/d/tcaplus_applications.html.markdown, website/docs/r/ccn_attachment.html.markdown
resource `tencentcloud_ccn_attachment`add parameter `ccn_uin`
=> resource `tencentcloud_ccn_attachment`add parameter `ccn_uin`

website/docs/index.html.markdown
=> Fix for some minor language issues.

tencentcloud/resource_tc_cdn_domain.go, tencentcloud/resource_tc_dayu_ddos_policy.go, tencentcloud/service_tencentcloud_vpc.go
=> vpc DescribeVpcs panic 

tencentcloud/service_tencentcloud_mysql.go
=> fix paging logic

tencentcloud/resource_tc_mysql_instance.go, tencentcloud/resource_tc_mysql_instance_test.go, tencentcloud/resource_tc_mysql_readonly_instance.go
Rewrite tag creation part in resource mysql_instance with tencentcloud_tag service package
=> resource_tc_mysql_instance patch

CHANGELOG.md, tencentcloud/resource_tc_cdn_domain.go
fix incorrect setting `server_certificate_config`,`client_certificate_config` caused the program to crash.
=> `tencentcloud_cdn_domain` fix   incorrect setting case crash.

CHANGELOG.md, tencentcloud/resource_tc_gaap_http_domain_test.go, tencentcloud/resource_tc_gaap_layer4_listener_test.go, tencentcloud/resource_tc_gaap_layer7_listener_test.go, tencentcloud/service_tencentcloud_gaap.go
when destroy gaap listener, it may reports InvalidParameter error, add error code check to fix it
=> fix: gaap listener destroy may fail

vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cam/v20190116/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cam/v20190116/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdb/v20170320/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdb/v20170320/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdn/v20180606/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm/v20170312/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dayu/v20180709/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dayu/v20180709/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/es/v20180416/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/es/v20180416/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/monitor/v20180724/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/postgres/v20170312/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/redis/v20180412/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/redis/v20180412/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/scf/v20180416/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/sqlserver/v20180328/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/sqlserver/v20180328/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tag/v20180813/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tag/v20180813/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tcaplusdb/v20190823/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tcaplusdb/v20190823/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/models.go
1. go mod vendor for other service except mongo
=> [go mod vendor for other service except mongo]

CHANGELOG.md, tencentcloud/resource_tc_instance.go
=== RUN   TestAccTencentCloudInstanceWithPrepaidChargeType
=== PAUSE TestAccTencentCloudInstanceWithPrepaidChargeType
=== CONT  TestAccTencentCloudInstanceWithPrepaidChargeType
--- PASS: TestAccTencentCloudInstanceWithPrepaidChargeType (244.57s)
=> fix accidentally fail to delete prepaid instance

CHANGELOG.md, examples/tencentcloud-vpn/main.tf, tencentcloud/resource_tc_vpn_connection.go, tencentcloud/resource_tc_vpn_gateway.go, tencentcloud/resource_tc_vpn_gateway_test.go, tencentcloud/service_tencentcloud_tke.go, website/docs/r/vpn_connection.html.markdown, website/docs/r/vpn_gateway.html.markdown
1. bugfix vpc_id for vpn connection
2. bugfix vpc_id for vpn gateway
=> [vpn connection fix]

CHANGELOG.md, tencentcloud/resource_tc_vpn_connection.go, tencentcloud/resource_tc_vpn_gateway.go, tencentcloud/service_tencentcloud_vpc.go, website/docs/r/vpn_connection.html.markdown, website/docs/r/vpn_gateway.html.markdown
➜  terraform-provider-tencentcloud git:(master) make testacc TESTARGS="-run=TestAccTencentCloudVpnConnection_basic"
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudVpnConnection_basic -timeout 120m
?   	github.com/terraform-providers/terraform-provider-tencentcloud	[no test files]
PASS
ok  	github.com/terraform-providers/terraform-provider-tencentcloud/gendoc	(cached) [no tests to run]
=== RUN   TestAccTencentCloudVpnConnection_basic
--- PASS: TestAccTencentCloudVpnConnection_basic (314.13s)
PASS
ok  	github.com/terraform-providers/terraform-provider-tencentcloud/tencentcloud	315.285s
?   	github.com/terraform-providers/terraform-provider-tencentcloud/tencentcloud/connectivity	[no test files]
? …
=> ccn forcenew issue when repeatly apply

CHANGELOG.md, tencentcloud/resource_tc_instance.go, tencentcloud/resource_tc_instance_test.go, tencentcloud/service_tencentcloud_cvm.go, website/docs/r/instance.html.markdown
go test -v ./tencentcloud/ -test.run TestAccTencentCloudInstanceWithNetwork
=== RUN   TestAccTencentCloudInstanceWithNetwork
=== PAUSE TestAccTencentCloudInstanceWithNetwork
=== CONT  TestAccTencentCloudInstanceWithNetwork
--- PASS: TestAccTencentCloudInstanceWithNetwork (88.49s)
PASS
ok      github.com/terraform-providers/terraform-provider-tencentcloud/tencentcloud     88.500s
=> feature: update internet_max_bandwidth_out with no forceNew operation

CHANGELOG.md, tencentcloud/resource_tc_vpn_connection.go, tencentcloud/resource_tc_vpn_customer_gateway.go, tencentcloud/service_tencentcloud_vpc.go
=> update inconsistent state when deleted on console

CHANGELOG.md, tencentcloud/resource_tc_cbs_storage_attachment.go, tencentcloud/resource_tc_cbs_storage_attachment_test.go, tencentcloud/resource_tc_eip_association.go, tencentcloud/resource_tc_eip_association_test.go, tencentcloud/resource_tc_route_table_entry.go, tencentcloud/resource_tc_route_table_entry_test.go, tencentcloud/resource_tc_vpc_acl_attachment.go, tencentcloud/resource_tc_vpc_acl_attachment_test.go, tencentcloud/resource_tc_vpc_acl_test.go, website/docs/r/cbs_storage_attachment.html.markdown, website/docs/r/eip_association.html.markdown, website/docs/r/route_table_entry.html.markdown, website/docs/r/vpc_acl_attachment.html.markdown
* Resource: `tencentcloud_cbs_storage_attachment` support import.
* Resource: `tencentcloud_eip_association` support import.
* Resource: `tencentcloud_route_table_entry` support import.
* Resource: `tencentcloud_acl_attachment` support import.
=> attachment support import

CHANGELOG.md, examples/tencentcloud-clb/main.tf, tencentcloud/data_source_tc_clb_target_groups.go, tencentcloud/data_source_tc_clb_target_groups_test.go, tencentcloud/extension_clb.go, tencentcloud/provider.go, tencentcloud/resource_tc_clb_listener_rule.go, tencentcloud/resource_tc_clb_listener_rule_test.go, tencentcloud/resource_tc_clb_target_group.go, tencentcloud/resource_tc_clb_target_group_attachment.go, tencentcloud/resource_tc_clb_target_group_attachment_test.go, tencentcloud/resource_tc_clb_target_group_instance_attachment.go, tencentcloud/resource_tc_clb_target_group_instance_attachment_test.go, tencentcloud/resource_tc_clb_target_group_test.go, tencentcloud/service_tencentcloud_clb.go, website/docs/d/clb_target_groups.html.markdown, website/docs/r/clb_listener_rule.html.markdown, website/docs/r/clb_target_group.html.markdown, website/docs/r/clb_target_group_attachment.html.markdown, website/docs/r/clb_target_group_instance_attachment.html.markdown, website/docs/r/clb_targetgroup.html.markdown, website/docs/r/clb_tg_instance_attachment.html.markdown, website/tencentcloud.erb
terraform-provider-tencentcloud guojunchu$ make testacc TESTARGS="-run TestAccTencentCloudClbTGAttachmentInstance_basic"
TF_ACC=1 go test ./... -v -run TestAccTencentCloudClbTGAttachmentInstance_basic -timeout 120m
PASS
=== RUN   TestAccTencentCloudClbTGAttachmentInstance_basic
--- PASS: TestAccTencentCloudClbTGAttachmentInstance_basic (13.08s)
PASS
ok      github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud       16.360s
? …
=> add  clb targetgroup

CHANGELOG.md, tencentcloud/resource_tc_clb_instance.go
1. fix tag creation
----------
➜  terraform-provider-tencentcloud git:(master) ✗ make testacc TESTARGS="-run=TestAccTencentCloudClbInstance_open"
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudClbInstance_open -timeout 120m
?   	github.com/tencentcloudstack/terraform-provider-tencentcloud	[no test files]
PASS
ok  	github.com/tencentcloudstack/terraform-provider-tencentcloud/gendoc	0.836s [no tests to run]
=== RUN   TestAccTencentCloudClbInstance_open
=== PAUSE TestAccTencentCloudClbInstance_open
=== CONT  TestAccTencentCloudClbInstance_open
--- PASS: TestAccTencentCloudClbInstance_open (17.57s)
PASS
ok  	github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud	18.198s
? …
=> [bug fix for clb tags]

CHANGELOG.md, tencentcloud/resource_tc_clb_instance.go, tencentcloud/resource_tc_clb_instance_test.go, tencentcloud/resource_tc_instance.go, tencentcloud/resource_tc_redis_backup_config.go, tencentcloud/resource_tc_redis_instance.go, website/docs/r/clb_instance.html.markdown, website/docs/r/redis_backup_config.html.markdown, website/docs/r/redis_instance.html.markdown
```
make testacc TESTARGS=" -run=TestAccTencentCloudClbInstance_open"
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudClbInstance_open -timeout 120m
PASS
ok      github.com/tencentcloudstack/terraform-provider-tencentcloud/gendoc     2.465s [no tests to run]
=== RUN   TestAccTencentCloudClbInstance_open
=== PAUSE TestAccTencentCloudClbInstance_open
=== CONT  TestAccTencentCloudClbInstance_open
--- PASS: TestAccTencentCloudClbInstance_open (15.56s)
PASS
ok      github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud       17.060s
? …
```
=> fix CLB force new bug and document issues

CHANGELOG.md, tencentcloud/resource_tc_kubernetes_scale_worker.go, tencentcloud/resource_tc_kubernetes_scale_worker_test.go, tencentcloud/service_tencentcloud_tke.go, website/docs/r/kubernetes_scale_worker.html.markdown
make testacc TESTARGS="-run TestAccTencentCloudTkeScaleWorkerResource"
TF_ACC=1 go test ./... -v -run TestAccTencentCloudTkeScaleWorkerResource -timeout 120m
PASS
=== RUN   TestAccTencentCloudTkeScaleWorkerResource
--- PASS: TestAccTencentCloudTkeScaleWorkerResource (327.40s)
PASS
ok      github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud       329.966s
?       github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/connectivity  [no test files]
? …
=> add tke scale worker "labels"

CHANGELOG.md, tencentcloud/resource_tc_redis_instance.go, tencentcloud/service_tencentcloud_redis.go, website/docs/r/redis_instance.html.markdown
1. fix incorrect number of mem_size attr.
=> [bugfix for redis]

CHANGELOG.md, examples/tencentcloud-cos/main.tf, examples/tencentcloud-cos/variables.tf, tencentcloud/provider.go, tencentcloud/resource_tc_clb_listener.go, tencentcloud/resource_tc_cos_bucket_policy.go, tencentcloud/resource_tc_cos_bucket_policy_test.go, tencentcloud/resource_tc_kubernetes_as_scaling_group.go, tencentcloud/resource_tc_kubernetes_as_scaling_group_test.go, tencentcloud/service_tencentcloud_cos.go, tencentcloud/service_tencentcloud_tke.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/expand_json.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/flatten_json.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/normalize_json.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/suppress_json_diff.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/float.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/int.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/list.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/meta.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/network.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/strings.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/testing.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/time.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/uuid.go, vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/web.go, vendor/modules.txt, website/docs/r/kubernetes_as_scaling_group.html.markdown
--tke resource 
make testacc TESTARGS="-run=TestAccTencentCloudTkeAsResource"  
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudTkeAsResource -timeout 120m
?   	github.com/tencentcloudstack/terraform-provider-tencentcloud	[no test files]
PASS
ok  	github.com/tencentcloudstack/terraform-provider-tencentcloud/gendoc	0.680s [no tests to run]
=== RUN   TestAccTencentCloudTkeAsResource
--- PASS: TestAccTencentCloudTkeAsResource (320.40s)
PASS
ok  	github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud	321.034s
?   	github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/connectivity	[no test files]
?   	github.com/tencentcloudstack/terraform-provider-tencentcloud/t …
=> modify tke config and new cos bucket policy file

tencentcloud/provider.go, website/docs/d/tcr_instances.html.markdown, website/docs/d/tcr_namespaces.html.markdown, website/docs/d/tcr_repositories.html.markdown, website/docs/d/tcr_tokens.html.markdown, website/docs/r/cos_bucket_policy.html.markdown, website/docs/r/tcr_instance.html.markdown, website/docs/r/tcr_namespace.html.markdown, website/docs/r/tcr_repository.html.markdown, website/docs/r/tcr_token.html.markdown, website/tencentcloud.erb
1. add cos bucket policy doc file.
2. modify TCR to Tencent Container Registry（TCR）
=> add cos bucket policy and modify tcr doc name

CHANGELOG.md, tencentcloud/data_source_tc_instances.go, tencentcloud/resource_tc_instance.go, tencentcloud/service_tencentcloud_tcr.go, website/docs/d/instances.html.markdown, website/docs/r/instance.html.markdown
```
+ create
+ resource "tencentcloud_tcr_instance" "example" {
+ delete_bucket      = true
+ id                 = (known after apply)
+ instance_type      = "standard"
+ internal_end_point = (known after apply)
+ name               = "testacctcrinstance"
+ public_domain      = (known after apply)
+ status             = (known after apply)
+ tags               = {
+ "test"  = "test"
+ "test1" = "test1"
}
}
Plan: 1 to add, 0 to change, 0 to destroy.
Do you want to perform these actions?
Terraform will perform the actions described above.
Only 'yes' will be accepted to approve.
Enter a value: yes
tencentcloud_tcr_instance.example: …
```
=> modify resource tencentcloud_tcr_instance and resource tencentcloud_instance

CHANGELOG.md, tencentcloud/resource_tc_kubernetes_cluster.go, tencentcloud/service_tencentcloud_tke.go
`tencentcloud_kubernetes_cluster` add `upgrade_instances_follow_cluster` for upgrade all instances of cluster.
=> tencentcloud_kubernetes_cluster add upgrade_instances_follow_cluster

CHANGELOG.md, tencentcloud/resource_tc_kubernetes_cluster.go
=> tke upgrade instances timeout depend on instance number

CHANGELOG.md, tencentcloud/resource_tc_scf_function.go
fix:`tencentcloud_scf_function` filed `cls_logset_id` and `cls_logset_id` change to Computed
=> filed `cls_logset_id` and `cls_logset_id` change to Computed

CHANGELOG.md, tencentcloud/resource_tc_kubernetes_cluster.go, website/docs/r/kubernetes_cluster.html.markdown, website/docs/r/kubernetes_scale_worker.html.markdown, website/docs/r/vpn_connection.html.markdown
fix:TkeCvmCreateInfo.data_disk.disk_type support CLOUD_HSSD
=> fix:TkeCvmCreateInfo.data_disk.disk_type support CLOUD_HSSD

tencentcloud/resource_tc_tcr_instance.go
tcr instance support modify tags
=> tcr support modify tags

tencentcloud/resource_tc_kubernetes_addon_attachment.go, tencentcloud/resource_tc_kubernetes_addon_attachment_test.go, website/docs/r/kubernetes_addon_attachment.html.markdown
=> fix: tke addon - using default version

tencentcloud/resource_tc_monitor_tmp_exporter_integration_test.go, tencentcloud/service_tencentcloud_monitor.go
update exporter integration test
=> fix: update exporter integration test

tencentcloud/data_source_tc_eks_cluster_credential.go, tencentcloud/resource_tc_monitor_tmp_tke_cluster_agent.go, tencentcloud/resource_tc_monitor_tmp_tke_global_notification.go, tencentcloud/resource_tc_monitor_tmp_tke_global_notification_test.go, website/docs/r/monitor_tmp_tke_cluster_agent.html.markdown, website/docs/r/monitor_tmp_tke_global_notification.html.markdown
=> fix: update irregular type

tencentcloud/resource_tc_dnspod_record.go, tencentcloud/resource_tc_dnspod_record_test.go, website/docs/r/dnspod_record.html.markdown
=> feat: dnspod record import

tencentcloud/basic_test.go, tencentcloud/resource_tc_cos_bucket_domain_certificate_attachment_test.go
adjust the account type to common for the cos_bucket_domain_certificate_attachment_test
=> adjust the account type to common for the cos_bucket_domain_certificate_attachment_test

tencentcloud/resource_tc_monitor_tmp_alert_rule.go, website/docs/r/monitor_tmp_alert_rule.html.markdown
=> fix: maintenance doc

tencentcloud/resource_tc_dnspod_domain_instance_test.go, tencentcloud/service_tencentcloud_dnspod.go
=> fix: dnspod unit update

go.mod
=> fix: go mod

.changelog/1367.txt, tencentcloud/resource_tc_vpc_bandwidth_package.go
=> fix: modify bandwidth_package

tencentcloud/resource_tc_kubernetes_cluster_attachment_test.go, tencentcloud/resource_tc_kubernetes_cluster_endpoint_test.go
tencentcloud_kubernetes_cluster_endpoint:
remove the unused resource
tencentcloud_kubernetes_cluster_attachment:
fix the dangling resource
=> fix: adjust  test case

tencentcloud/resource_tc_cos_bucket_test.go
^qcs::cam::uin/\\\\d+:uin/\\\\d+$
to:
^qcs::cam::uin/\\d+:uin/\\d+$
=> fix: adjust compile regex

.changelog/1379.txt, tencentcloud/resource_tc_vpc_bandwidth_package.go
=> fix: modify vpc_bandwidth

.changelog/1407.txt, tencentcloud/resource_tc_monitor_tmp_alert_rule.go, tencentcloud/resource_tc_monitor_tmp_alert_rule_test.go
=> fix: alert_rule optimization

.changelog/1417.txt, go.mod, go.sum, tencentcloud/basic_test.go, tencentcloud/connectivity/client.go, tencentcloud/internal/helper/transform.go, tencentcloud/provider.go, tencentcloud/resource_tc_dbbrain_security_audit_log_export_task.go, tencentcloud/resource_tc_dbbrain_security_audit_log_export_task_test.go, tencentcloud/resource_tc_dbbrain_sql_filter.go, tencentcloud/resource_tc_dbbrain_sql_filter_test.go, tencentcloud/resource_tc_mysql_account_test.go, tencentcloud/service_tencentcloud_dbbrain.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dbbrain/LICENSE, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dbbrain/v20210527/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dbbrain/v20210527/errors.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dbbrain/v20210527/models.go, vendor/modules.txt, website/docs/r/dbbrain_security_audit_log_export_task.html.markdown, website/docs/r/dbbrain_sql_filter.html.markdown, website/tencentcloud.erb
tencentcloud_dbbrain_sql_filter
tencentcloud_dbbrain_security_audit_log_export_task
=> feat/support DBBrain resource

tencentcloud/basic_test.go, tencentcloud/resource_tc_kubernetes_scale_worker_test.go
fix e2e issues for TestAccTencentCloudTkeResourceLogs  and TestAccTencentCloudTkeResourceBasic
=> fix:e2e issues for TestAccTencentCloudTkeResourceLogs  and TestAccTencentCloudTkeResourceBasic

.changelog/1439.txt, tencentcloud/resource_tc_kubernetes_node_pool.go
optimize scaling_group_project_id logic in node pool
=> Feat/optimize scaling_group_project_id logic in node pool

tencentcloud/data_source_tc_teo_bot_managed_rules.go
=> fix: opt param

.changelog/1450.txt, tencentcloud/resource_tc_cam_role_policy_attachment_test.go
=> fix: modify cam unit

tencentcloud/data_source_tc_enis_test.go
=> fix: eni unit

tencentcloud/resource_tc_monitor_tmp_tke_record_rule_yaml_test.go
=> fix: tmp RecordRule unit

.changelog/1452.txt, tencentcloud/resource_tc_cam_service_linked_role.go, tencentcloud/resource_tc_cam_service_linked_role_test.go, website/docs/r/cam_service_linked_role.html.markdown
support for multiple qcs_service_name
=> fix: support for multiple qcs_service_name

tencentcloud/resource_tc_tem_app_config_test.go, tencentcloud/resource_tc_tem_application_test.go, tencentcloud/resource_tc_tem_environment_test.go, tencentcloud/resource_tc_tem_gateway_test.go, tencentcloud/resource_tc_tem_log_config_test.go, tencentcloud/resource_tc_tem_scale_rule_test.go, tencentcloud/resource_tc_tem_workload_test.go
=> fix: modify tem unit name

tencentcloud/common.go, tencentcloud/provider.go, tencentcloud/resource_tc_cam_user_saml_config.go, tencentcloud/resource_tc_cam_user_saml_config_test.go, tencentcloud/service_tencentcloud_cam.go, website/docs/r/cam_user_saml_config.html.markdown, website/tencentcloud.erb
=> feat: support cam saml config

.changelog/1520.txt, tencentcloud/resource_tc_tem_application_service.go, tencentcloud/resource_tc_tem_application_service_test.go
support IP query when modifying the type
=> fix: support IP query when modifying the type

.changelog/1519.txt, go.mod, go.sum, tencentcloud/provider.go, tencentcloud/resource_tc_kubernetes_serverless_node_pool.go, tencentcloud/resource_tc_kubernetes_serverless_node_pool_test.go, tencentcloud/service_tencentcloud_tke.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525/errors.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525/models.go, vendor/modules.txt, website/docs/r/kubernetes_serverless_node_pool.html.markdown, website/tencentcloud.erb
tke support serverless node pool
=> feat: init tke serverless node pool feature

.changelog/1538.txt, tencentcloud/resource_tc_teo_rule_engine.go, tencentcloud/resource_tc_teo_rule_engine_test.go, website/docs/r/teo_rule_engine.html.markdown
=> fix: modify rule engine

tencentcloud/resource_tc_pts_project_test.go, tencentcloud/resource_tc_tem_app_config_test.go, tencentcloud/resource_tc_tem_log_config_test.go
=> fix: modify unit

.changelog/1551.txt, tencentcloud/resource_tc_vpc_bandwidth_package.go, website/docs/r/vpc_bandwidth_package.html.markdown
support internet_max_bandwidth
=> fix: support internet_max_bandwidth

tencentcloud/resource_tc_elasticsearch_instance_test.go
update case logic to "basic" upgrade to "platinum".
ignore the basic_security_type in the import process cause it is unacceptance when the type is platinum.
=> adjust es e2e case

.changelog/1598.txt, tencentcloud/resource_tc_mysql_account.go, tencentcloud/resource_tc_mysql_account_test.go, website/docs/r/mysql_account.html.markdown
=> feat: support import

tencentcloud/resource_tc_monitor_grafana_integration.go, website/docs/r/monitor_grafana_integration.html.markdown
tencentcloud_monitor_grafana_integration  add example
=> fix: fix doc

.changelog/1605.txt, tencentcloud/resource_tc_mysql_instance.go, tencentcloud/resource_tc_mysql_instance_test.go
mysql import support vpc and subnet
=> fix: suport import vpc

tencentcloud/resource_tc_teo_zone_test.go
=> fix: stop teo zone test

tencentcloud/basic_test.go, tencentcloud/resource_tc_ci_bucket_pic_style_test.go
=> fix: support init

.changelog/1611.txt, tencentcloud/provider.go, tencentcloud/resource_tc_monitor_tmp_manage_grafana_attachment.go, tencentcloud/resource_tc_monitor_tmp_manage_grafana_attachment_test.go, tencentcloud/service_tencentcloud_monitor.go, website/docs/r/monitor_tmp_manage_grafana_attachment.html.markdown, website/tencentcloud.erb
=> feat: support manage grafana

tencentcloud/resource_tc_teo_dns_record.go, tencentcloud/resource_tc_teo_dns_record_test.go, website/docs/r/teo_dns_record.html.markdown
Stop the automated test of tencentcloud_teo_dns_record
=> fix: Stop the automated test of tencentcloud_teo_dns_record

.changelog/1627.txt, tencentcloud/data_source_tc_ssm_secret_versions.go, tencentcloud/extension_postgresql.go, tencentcloud/extension_ssm.go
fix the #1620 
return null instead of raising the error introduced by SDK(ResourceNotFound).
=> fix:return null when the resource is not found

go.mod, go.sum, tencentcloud/basic_test.go, tencentcloud/data_source_tc_tat_agent.go, tencentcloud/data_source_tc_tat_agent_test.go, tencentcloud/data_source_tc_tat_invoker_records.go, tencentcloud/data_source_tc_tat_invoker_records_test.go, tencentcloud/provider.go, tencentcloud/resource_tc_tat_invocation_command_attachment.go, tencentcloud/resource_tc_tat_invocation_command_attachment_test.go, tencentcloud/resource_tc_tat_invocation_invoke_attachment.go, tencentcloud/resource_tc_tat_invocation_invoke_attachment_test.go, tencentcloud/resource_tc_tat_invoker_config.go, tencentcloud/resource_tc_tat_invoker_config_test.go, tencentcloud/service_tencentcloud_tat.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tat/v20201028/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tat/v20201028/errors.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tat/v20201028/models.go, vendor/modules.txt, website/docs/d/tat_agent.html.markdown, website/docs/d/tat_invoker_records.html.markdown, website/docs/r/tat_invocation_command_attachment.html.markdown, website/docs/r/tat_invocation_invoke_attachment.html.markdown, website/docs/r/tat_invoker_config.html.markdown, website/tencentcloud.erb
=> feat: support tat

.changelog/1760.txt, tencentcloud/data_source_tc_tcr_image_manifests.go, tencentcloud/data_source_tc_tcr_image_manifests_test.go, tencentcloud/data_source_tc_tcr_tag_retention_execution_tasks.go, tencentcloud/data_source_tc_tcr_tag_retention_execution_tasks_test.go, tencentcloud/internal/helper/transform.go, tencentcloud/provider.go, tencentcloud/resource_tc_tcr_tag_retention_rule.go, tencentcloud/service_tencentcloud_tcr.go, website/docs/d/tcr_image_manifests.html.markdown, website/docs/d/tcr_tag_retention_execution_tasks.html.markdown, website/tencentcloud.erb
data source:
tencentcloud_tcr_image_manifests
tencentcloud_tcr_tag_retention_execution_tasks
=> support tcr:  data source

.changelog/1776.txt, tencentcloud/data_source_tc_dbbrain_db_space_status.go, tencentcloud/data_source_tc_dbbrain_db_space_status_test.go, tencentcloud/data_source_tc_dbbrain_slow_logs.go, tencentcloud/data_source_tc_dbbrain_slow_logs_test.go, tencentcloud/data_source_tc_dbbrain_sql_templates.go, tencentcloud/data_source_tc_dbbrain_sql_templates_test.go, tencentcloud/provider.go, tencentcloud/service_tencentcloud_dbbrain.go, website/docs/d/dbbrain_db_space_status.html.markdown, website/docs/d/dbbrain_slow_logs.html.markdown, website/docs/d/dbbrain_sql_templates.html.markdown, website/tencentcloud.erb
data source:	
tencentcloud_dbbrain_slow_logs
tencentcloud_dbbrain_sql_templates
tencentcloud_dbbrain_db_space_status
=> support dbbrain data source

.changelog/1900.txt, tencentcloud/data_source_tc_tcr_replication_instance_create_tasks.go, tencentcloud/data_source_tc_tcr_replication_instance_create_tasks_test.go, tencentcloud/data_source_tc_tcr_replication_instance_sync_status.go, tencentcloud/data_source_tc_tcr_tag_retention_execution_tasks.go, tencentcloud/data_source_tc_tcr_tag_retention_execution_tasks_test.go, tencentcloud/data_source_tc_tcr_tag_retention_executions.go, tencentcloud/data_source_tc_tcr_tag_retention_executions_test.go, tencentcloud/provider.go, tencentcloud/service_tencentcloud_tcr.go, website/docs/d/tcr_replication_instance_create_tasks.html.markdown, website/docs/d/tcr_replication_instance_sync_status.html.markdown, website/docs/d/tcr_tag_retention_execution_tasks.html.markdown, website/docs/d/tcr_tag_retention_executions.html.markdown, website/tencentcloud.erb
tencentcloud_tcr_tag_retention_executions
tencentcloud_tcr_replication_instance_create_tasks
tencentcloud_tcr_replication_instance_sync_status
=> support tcr: data source

.changelog/1993.txt, tencentcloud/data_source_tc_ssl_certificates.go, website/docs/d/ssl_certificates.html.markdown
=> fix: support dv_auths

.changelog/2081.txt, tencentcloud/data_source_tc_monitor_alarm_notices.go, tencentcloud/data_source_tc_monitor_alarm_notices_test.go, website/docs/d/monitor_alarm_notices.html.markdown
=> feat: support amp_consumer_id

.changelog/2116.txt, tencentcloud/resource_tc_tcr_service_account.go, website/docs/r/tcr_service_account.html.markdown
Update the desc for field `permissions.actions`.
=> adjust doc desc:tencentcloud_tcr_service_account

.changelog/2115.txt, tencentcloud/provider.go, tencentcloud/resource_tc_cam_mfa_flag.go, tencentcloud/resource_tc_cam_mfa_flag_test.go, tencentcloud/resource_tc_ssl_commit_certificate_information.go, tencentcloud/resource_tc_ssl_commit_certificate_information_test.go, tencentcloud/resource_tc_ssl_pay_certificate.go, tencentcloud/service_tencentcloud_cam.go, website/docs/r/cam_mfa_flag.html.markdown, website/docs/r/ssl_pay_certificate.html.markdown, website/tencentcloud.erb
New resources:
Sub-user login protection
=> feat: resource mfaFlag

CHANGELOG.md
update changelog of release version 1.81.25
=> docs: update changelog of release version 1.81.25

CHANGELOG.md
add changelog of release version 1.81.26
=> docs: add changelog of release version 1.81.26

CHANGELOG.md
add changelog of release version v1.81.27
=> docs: add changelog of release version v1.81.27

CHANGELOG.md
add changelog of version v1.81.28
=> docs: add changelog of version v1.81.28

CHANGELOG.md
add release changelog of version v1.81.29
=> docs: add release changelog of version v1.81.29

CHANGELOG.md
add changelog of release version v1.81.30
=> docs: add changelog of release version v1.81.30

CHANGELOG.md
add changelog of release version v1.81.31
=> docs: add changelog of release version v1.81.31

CHANGELOG.md
add changelog of version v1.81.32
=> docs: add changelog of version v1.81.32

.changelog/2179.txt, tencentcloud/provider.go, tencentcloud/resource_tc_mps_enable_schedule_config.go, tencentcloud/resource_tc_mps_enable_schedule_config_test.go, tencentcloud/resource_tc_mps_schedule.go, tencentcloud/resource_tc_mps_schedule_test.go, tencentcloud/service_tencentcloud_mps.go, website/docs/r/mps_enable_schedule_config.html.markdown, website/docs/r/mps_schedule.html.markdown, website/tencentcloud.erb
tencentcloud_mps_schedule
tencentcloud_mps_enable_schedule_config
=> support mps schedule resource

.changelog/2185.txt, tencentcloud/basic_test.go, tencentcloud/data_source_tc_mps_schedules.go, tencentcloud/data_source_tc_mps_schedules_test.go, tencentcloud/provider.go, tencentcloud/service_tencentcloud_mps.go, website/docs/d/mps_schedules.html.markdown, website/tencentcloud.erb
=> support data source tencentcloud_mps_schedules

.changelog/2188.txt, tencentcloud/provider.go, tencentcloud/resource_tc_mps_edit_media_operation.go, tencentcloud/resource_tc_mps_edit_media_operation_test.go, tencentcloud/resource_tc_mps_process_live_stream_operation.go, tencentcloud/resource_tc_mps_process_live_stream_operation_test.go, website/docs/r/mps_edit_media_operation.html.markdown, website/docs/r/mps_process_live_stream_operation.html.markdown, website/tencentcloud.erb
tencentcloud_mps_edit_media_operation
tencentcloud_mps_process_live_stream_operation
=> support mps operation

.changelog/2191.txt, go.mod, go.sum, tencentcloud/data_source_tc_organization_org_auth_node.go, tencentcloud/data_source_tc_organization_org_auth_node_test.go, tencentcloud/provider.go, tencentcloud/resource_tc_organization_org_member_auth_identity_attachment.go, tencentcloud/resource_tc_organization_org_member_auth_identity_attachment_test.go, tencentcloud/service_tencentcloud_organization.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/organization/v20210331/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/organization/v20210331/errors.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/organization/v20210331/models.go, vendor/modules.txt, website/docs/d/organization_org_auth_node.html.markdown, website/docs/r/organization_org_member_auth_identity_attachment.html.markdown, website/tencentcloud.erb
=> Feat/organization 

.changelog/2229.txt, tencentcloud/provider.go, tencentcloud/resource_tc_organization_quit_organization_operation.go, tencentcloud/resource_tc_organization_quit_organization_operation_test.go, website/docs/r/organization_quit_organization_operation.html.markdown, website/tencentcloud.erb
=> feat: organization

.changelog/2218.txt, go.mod, go.sum, tencentcloud/data_source_tc_dnspod_domain_list.go, tencentcloud/data_source_tc_dnspod_domain_list_test.go, tencentcloud/provider.go, tencentcloud/service_tencentcloud_dnspod.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/response.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/ratelimitretry.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dnspod/v20210323/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dnspod/v20210323/errors.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dnspod/v20210323/models.go, vendor/modules.txt, website/docs/d/dnspod_domain_list.html.markdown, website/tencentcloud.erb
Add datasource of dnspod domain list
=> feat(dnspod): Add datasource of dnspod domain list

.changelog/2233.txt, go.mod, go.sum, tencentcloud/data_source_tc_dlc_check_data_engine_image_can_be_rollback.go, tencentcloud/data_source_tc_dlc_check_data_engine_image_can_be_rollback_test.go, tencentcloud/provider.go, tencentcloud/resource_tc_dlc_add_users_to_work_group_attachment.go, tencentcloud/resource_tc_dlc_add_users_to_work_group_attachment_test.go, tencentcloud/resource_tc_dlc_store_location_config.go, tencentcloud/resource_tc_dlc_store_location_config_test.go, tencentcloud/service_tencentcloud_dlc.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dlc/v20210125/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dlc/v20210125/errors.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dlc/v20210125/models.go, vendor/modules.txt, website/docs/d/dlc_check_data_engine_image_can_be_rollback.html.markdown, website/docs/r/dlc_add_users_to_work_group_attachment.html.markdown, website/docs/r/dlc_store_location_config.html.markdown, website/tencentcloud.erb
=> feat: dlc attach

.changelog/2242.txt, tencentcloud/data_source_tc_dnspod_record_analytics.go
=> fix(dnspod): set info error

.changelog/2245.txt, tencentcloud/data_source_tc_dlc_check_data_engine_image_can_be_upgrade.go, tencentcloud/data_source_tc_dlc_check_data_engine_image_can_be_upgrade_test.go, tencentcloud/provider.go, tencentcloud/resource_tc_dlc_data_engine.go, tencentcloud/resource_tc_dlc_data_engine_test.go, tencentcloud/resource_tc_dlc_rollback_data_engine_image_operation.go, tencentcloud/resource_tc_dlc_rollback_data_engine_image_operation_test.go, tencentcloud/service_tencentcloud_dlc.go, website/docs/d/dlc_check_data_engine_image_can_be_upgrade.html.markdown, website/docs/r/dlc_data_engine.html.markdown, website/docs/r/dlc_rollback_data_engine_image_operation.html.markdown, website/tencentcloud.erb
=> feat: engine

.changelog/2246.txt, tencentcloud/resource_tc_kubernetes_cluster.go, tencentcloud/resource_tc_kubernetes_cluster_attachment.go, tencentcloud/resource_tc_kubernetes_scale_worker.go, website/docs/r/kubernetes_scale_worker.html.markdown
1、import node
2、fix the bug of adding cvm node to cluster
=> import node

CHANGELOG.md, website/tencentcloud.erb
=> docs: add changelog of v1.81.40

.changelog/2262.txt, go.mod, go.sum, tencentcloud/resource_tc_dlc_store_location_config.go, tencentcloud/resource_tc_dlc_store_location_config_test.go, tencentcloud/service_tencentcloud_dlc.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dlc/v20210125/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dlc/v20210125/errors.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dlc/v20210125/models.go, vendor/modules.txt, website/docs/r/dlc_store_location_config.html.markdown
=> feat: dlc store location

CHANGELOG.md
add changelog of version 1.81.42
=> docs: add changelog of version 1.81.42

CHANGELOG.md
add changelog of version v1.81.45
=> docs: add changelog of version v1.81.45

.changelog/2306.txt, tencentcloud/provider.go, tencentcloud/resource_tc_dnspod_snapshot_config.go, tencentcloud/resource_tc_dnspod_snapshot_config_test.go, tencentcloud/service_tencentcloud_dnspod.go, website/docs/r/dnspod_snapshot_config.html.markdown, website/tencentcloud.erb
=> feat(dnspod): dnspod snapshot config

CHANGELOG.md
add changelog of version 1.81.46
=> docs: add changelog of version 1.81.46

CHANGELOG.md
=> docs: add changelog of v1.81.48

CHANGELOG.md
add changelog of version v1.81.50
=> docs: add changelog of version v1.81.50

.changelog/2357.txt, tencentcloud/service_tencentcloud_clb.go
clb tencentcloud_clb_target_group_attachment
=> feat: support async task

tencentcloud/resource_tc_ssl_deploy_certificate_instance_operation.go, website/docs/r/ssl_deploy_certificate_instance_operation.html.markdown
=> docs: update ssl example

CHANGELOG.md
=> docs: add changelog of v1.81.82

.changelog/2366.txt, tencentcloud/resource_tc_organization_org_member.go, tencentcloud/resource_tc_organization_org_member_email.go, tencentcloud/resource_tc_organization_org_member_test.go
=> fix: organization bug

CHANGELOG.md
=> docs: add changelog of v1.81.55

CHANGELOG.md
=> docs: add changelog of v1.81.57

.changelog/2398.txt, tencentcloud/provider.go, tencentcloud/resource_tc_clb_target_group_attachments.go, tencentcloud/resource_tc_clb_target_group_attachments_test.go, tencentcloud/service_tencentcloud_clb.go, tencentcloud/services/clb/resource_tc_clb_target_group_attachments.md
tencentcloud_clb_target_group_attachments
=> feat: clb attachments target group

tencentcloud/resource_tc_mysql_instance.go
=> feat: mysql support import

CHANGELOG.md
add changelog of version 1.81.58
=> docs: add changelog of version 1.81.58

CHANGELOG.md
=> docs: changelog of 1.81.59

CHANGELOG.md
add changelog of version 1.81.60
=> docs: add changelog of version 1.81.60

CHANGELOG.md
=> docs: add changelog of v1.81.63

.changelog/2457.txt, tencentcloud/services/clb/resource_tc_clb_redirection.go
fix get protocol and port nil ptr
=> fix: null pointer exception

.changelog/2460.txt, tencentcloud/services/dc/resource_tc_dcx.go, tencentcloud/services/dc/service_tencentcloud_dc.go
dcx create wait finish
https://andon.woa.com/micro/base/anstory-detail/?id=1099914
=> feat: wait createTunnel

CHANGELOG.md
add changelog of version v1.81.64
=> docs: add changelog of version v1.81.64

CHANGELOG.md
add changelog of version v1.81.67
=> docs: add changelog of version v1.81.67

.changelog/2494.txt, tencentcloud/services/vpc/service_tencentcloud_vpc.go
Supports more than one hundred data returns
`tencentcloud_security_groups`
=> feat: support pagination describe

.changelog/2506.txt, tencentcloud/services/dnspod/resource_tc_dnspod_record.go
fix modify dnspod record weight
=> fix: modify dnspod record weight

.changelog/2512.txt, tencentcloud/services/clb/data_source_tc_clb_attachments.go, website/docs/d/clb_attachments.html.markdown
datasource `tencentcloud_clb_attachments` add param `eni_ip`
=> feat: add para

.changelog/2520.txt, go.mod, go.sum, tencentcloud/provider.go, tencentcloud/provider.md, tencentcloud/services/tco/data_source_tc_organization_org_share_area.go, tencentcloud/services/tco/data_source_tc_organization_org_share_area.md, tencentcloud/services/tco/data_source_tc_organization_org_share_area_test.go, tencentcloud/services/tco/service_tencentcloud_organization.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/organization/v20210331/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/organization/v20210331/errors.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/organization/v20210331/models.go, vendor/modules.txt
add datasource `tencentcloud_organization_org_share_area`
=> feat: organization add datasource

.github/workflows/mkdocs.yml
=> feat: mkdoc path

.github/workflows/lint-pr.yml
feat: add action of pr title lint
=> feat: add action of pr title lint

.changelog/2551.txt, go.mod, go.sum, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cls/v20201016/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/json/encode.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/oidc_role_arn_provider.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/role_arn_credential.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/csip/v20221121/models.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tag/v20180813/models.go, vendor/modules.txt
=> fix(cvm): [116411403] fix the issue of invalid parameters

.changelog/2566.txt, tencentcloud/provider.md, tencentcloud/services/bh/resource_tc_dasb_acl.md, tencentcloud/services/bh/resource_tc_dasb_resource.go, tencentcloud/services/bh/resource_tc_dasb_resource.md, tencentcloud/services/bh/resource_tc_dasb_resource_test.go, website/docs/r/dasb_acl.html.markdown, website/docs/r/dasb_resource.html.markdown, website/tencentcloud.erb
=> feat(bh): [116578841] Add Dasb resource 

go.mod, go.sum, tencentcloud/provider.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/json/encode.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/oidc_role_arn_provider.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/role_arn_credential.go, vendor/modules.txt
=> fix(common): [116491106] fix common version 

.github/workflows/golangci-lint.yml
=> feat(ci): [117216621]golang-ci

.changelog/2603.txt, .changelog/2604.txt, go.mod, go.sum, tencentcloud/provider.go, tencentcloud/services/tco/extension_tco.go, tencentcloud/services/tco/resource_tc_organization_org_manage_policy.go, tencentcloud/services/tco/resource_tc_organization_org_manage_policy.md, tencentcloud/services/tco/resource_tc_organization_org_manage_policy_config.go, tencentcloud/services/tco/resource_tc_organization_org_manage_policy_config.md, tencentcloud/services/tco/resource_tc_organization_org_manage_policy_config_test.go, tencentcloud/services/tco/resource_tc_organization_org_manage_policy_target.go, tencentcloud/services/tco/resource_tc_organization_org_manage_policy_target.md, tencentcloud/services/tco/resource_tc_organization_org_manage_policy_target_test.go, tencentcloud/services/tco/resource_tc_organization_org_manage_policy_test.go, tencentcloud/services/tco/service_tencentcloud_organization.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/organization/v20210331/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/organization/v20210331/errors.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/organization/v20210331/models.go, vendor/modules.txt
add resource organization policy
=> feat(tco): [117095836]add resource organization policy 

tencentcloud/connectivity/transport.go
=> fix(iacExt): [116337119] Optimizing the code

.changelog/2598.txt, tencentcloud/services/clb/service_tencentcloud_clb.go
=> feat(clb): [116532977]support healthcheck don't checke parameter

.changelog/2641.txt, tencentcloud/services/cam/resource_tc_cam_role.go
=> feat(cam): [117556313]add computed

.changelog/2667.txt, tencentcloud/services/cls/resource_tc_cls_index.md, tencentcloud/services/cls/resource_tc_cls_index_test.go, website/docs/r/cls_index.html.markdown
adjust this example to fit Pulumi SDK generation.
The issue in Pulumi SDK generation:
=> feat(cls): [117803962] adjust cls index example to compatible pulumi generation

tencentcloud/services/clb/resource_tc_clb_instance.md, website/docs/r/clb_instance.html.markdown
fix docs:
`tencentcloud_clb_instance `
=> docs(clb): [117920570]Updated documentation

.changelog/2675.txt, tencentcloud/services/clb/resource_tc_clb_instance.go, tencentcloud/services/clb/resource_tc_clb_instance_test.go, website/docs/r/clb_instance.html.markdown
=> feat(clb): [117735262]support ipv6 param

tencentcloud/services/cvm/data_source_tc_cvm_instance_vnc_url_test.go, tencentcloud/services/cvm/data_source_tc_cvm_instances_modification_test.go, tencentcloud/services/cvm/data_source_tc_eip_address_quota_test.go, tencentcloud/services/cvm/data_source_tc_eip_network_account_type_test.go, tencentcloud/services/cvm/resource_tc_cvm_launch_template_default_version_test.go, tencentcloud/services/cvm/resource_tc_cvm_launch_template_version_test.go, tencentcloud/services/cvm/resource_tc_cvm_modify_instance_disk_type_test.go, tencentcloud/services/cvm/resource_tc_cvm_reboot_instance_test.go
add some cvm acctest:
- resource tencentcloud_cvm_launch_template_default_version
- resource tencentcloud_cvm_launch_template_version
- resource tencentcloud_cvm_reboot_instance
- resource tencentcloud_cvm_modify_instance_disk_type
- data tencentcloud_cvm_instance_vnc_url
- data tencentcloud_cvm_instances_modification
- data tencentcloud_eip_address_quota
- data tencentcloud_eip_network_account_type
=> test(cvm): [117971511] add some cvm acctest

.changelog/2707.txt, tencentcloud/services/apm/resource_tc_apm_instance.go, tencentcloud/services/apm/resource_tc_apm_instance.md, tencentcloud/services/apm/resource_tc_apm_instance_test.go, website/docs/r/apm_instance.html.markdown
=> fix(apm): [117999788] apm_instance add retry operator

.changelog/2717.txt, go.mod, go.sum, tencentcloud/services/vpc/data_source_tc_subnet.go, tencentcloud/services/vpc/data_source_tc_subnet.md, tencentcloud/services/vpc/data_source_tc_vpc_instances.go, tencentcloud/services/vpc/data_source_tc_vpc_subnets.go, tencentcloud/services/vpc/data_source_tc_vpc_subnets.md, tencentcloud/services/vpc/resource_tc_subnet.go, tencentcloud/services/vpc/resource_tc_subnet.md, tencentcloud/services/vpc/service_tencentcloud_vpc.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/errors.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/models.go, vendor/modules.txt, website/docs/d/subnet.html.markdown, website/docs/d/vpc_subnets.html.markdown, website/docs/r/subnet.html.markdown
=> feat(subnet): [118298157] support CDC

.changelog/2866.txt, tencentcloud/services/tke/resource_tc_kubernetes_cluster_attachment.go, tencentcloud/services/tke/resource_tc_kubernetes_cluster_attachment_extension.go, website/docs/r/kubernetes_cluster_attachment.html.markdown
=> feat(tke): [119910893] support taints and security_group for tencentcloud_kubernetes_cluster_attachment
