tencentcloud/resource_tc_instance.go
website/docs/r/instance.html.markdown

even though we can use terraform builtin function base64encode() to
generate base64 encoded string from raw text, we still provide this
option for users.
fix #4

support instance user_data_raw

---

CHANGELOG.md
tencentcloud/data_source_tc_security_group.go
tencentcloud/resource_tc_security_group.go

data/tencentcloud_security_group: `project_id` remote API return sometime is string type.
resource/tencentcloud_security_group: just like `data/tencentcloud_security_group`

bug fix project_id

---

CHANGELOG.md
tencentcloud/resource_tc_eip_association.go
tencentcloud/resource_tc_instance.go
website/docs/r/eip_association.html.markdown

BUG FIXIES:
* resource/tencentcloud_instance: fixed issue when data disks set as delete_with_instance not works.
* resource/tencentcloud_instance: if managed public_ip manually, please don't define `allocate_public_ip` ([#62](https://github.com/terraform-providers/terraform-provider-tencentcloud/issues/62)).
* resource/tencentcloud_eip_association: fixed issue when instances were manually deleted ([#60](https://github.com/terraform-providers/terraform-provider-tencentcloud/issues/60)).

bugfixed on tencentcloud_instance and tencentcloud_eip_association

---

tencentcloud/extension_mysql.go
tencentcloud/helper.go
tencentcloud/resource_tc_mysql_instance.go
tencentcloud/resource_tc_mysql_readonly_instance.go
tencentcloud/service_tencentcloud_mysql.go
website/docs/r/mysql_instance.html.markdown
website/docs/r/mysql_readonly_instance.html.markdown

If mysql has readonly instance or it is a readonly instance, it can't  be released immediately.

Readonly mysql  instance can't  be released immediately.

---

tencentcloud/connectivity/client.go

Valid choices: zh-CN, en-US.
Default value is zh-CN.

set  cpf.Language = "en-US"

---

CHANGELOG.md
tencentcloud/resource_tc_instance.go

This issue caused the cbs attach to fail

fix cvm data disk missing computed

---

tencentcloud/connectivity/client.go
tencentcloud/resource_tc_redis_instance_test.go

bug fix :
after delete redis, the instance cannot be pulled instead of the inst ance state becoming deleted.

bug fix :after delete redis, the instance info is nil

---

CHANGELOG.md
tencentcloud/resource_tc_mysql_instance.go

Resource: `tencentcloud_mysql_instance`: miss argument `availability_zone` causes the instance to be recreated.

Miss argument availability_zone  causes  mysql  recreated

---

CHANGELOG.md
tencentcloud/data_source_tc_gaap_http_domains.go
tencentcloud/resource_tc_gaap_http_domain.go

gaap http_domain some attributes `certificate_id`, `client_certificate_id`, `realserver_auth`, `basic_auth` and `gaap_auth` sometimes return `null`, set them default value when they are `null` to avoid user can't `terraform refresh`

Fix gaap nil error

---

tencentcloud/resource_tc_as_scaling_group_test.go
tencentcloud/resource_tc_cos_bucket_test.go

The Pre-Sweeper build step on TC was failing due to a panic. Fix the type mismatch in the sweeper functions that caused it.

Fix type mismatch in sweepers

---

CHANGELOG.md
tencentcloud/data_source_tc_gaap_layer7_listeners.go
tencentcloud/resource_tc_gaap_http_domain.go
tencentcloud/resource_tc_gaap_http_domain_test.go
tencentcloud/resource_tc_gaap_layer7_listener.go
tencentcloud/resource_tc_gaap_layer7_listener_test.go
website/docs/r/gaap_http_domain.html.markdown
website/docs/r/gaap_layer7_listener.html.markdown

Add import support:
- tencentcloud_gaap_layer7_listener
- tencentcloud_gaap_http_domain

Add more import support for gaap resources

---

website/docs/d/cam_role_policy_attachments.html.markdown
website/docs/d/cam_user_policy_attachments.html.markdown
website/docs/r/as_scaling_config.html.markdown
website/docs/r/cam_group.html.markdown
website/docs/r/cam_group_membership.html.markdown
website/docs/r/cam_group_policy_attachment.html.markdown
website/docs/r/cam_role_policy_attachment.html.markdown
website/docs/r/cam_user.html.markdown
website/docs/r/cam_user_policy_attachment.html.markdown
website/tencentcloud.erb

fix spelling issues and add erb file

fix spelling issues and add erb file

---

tencentcloud/extension_cvm.go
tencentcloud/resource_tc_key_pair.go

Fix failed to run terraform destroy in the first time when you have vms with sshkey(#194)

Fix key pair destroy

---

CHANGELOG.md
tencentcloud/data_source_tc_kubernetes_clusters.go
tencentcloud/extension_tke.go
tencentcloud/resource_tc_kubernetes_cluster.go
website/docs/r/kubernetes_cluster.html.markdown

Resource: `tencentcloud_kubernetes_cluster` cluster_os add new support: `centos7.6x86_64` and `ubuntu18.04.1 LTSx86_64` 
#199

tencentcloud_kubernetes_cluster add  new cluster_os 

---

CHANGELOG.md
tencentcloud/data_source_tc_subnet.go
tencentcloud/data_source_tc_vpc.go
tencentcloud/data_source_tc_vpc_instances.go
tencentcloud/data_source_tc_vpc_subnets.go
tencentcloud/resource_tc_kubernetes_as_scaling_group_test.go
tencentcloud/resource_tc_kubernetes_cluster_test.go
tencentcloud/resource_tc_kubernetes_scale_worker_test.go
tencentcloud/service_tencentcloud_vpc.go
website/docs/d/vpc_instances.html.markdown
website/docs/d/vpc_subnets.html.markdown

Data Source: `tencentcloud_vpc_instances` add new optional argument `is_default`.
Data Source: `tencentcloud_vpc_subnets` add new output argument `availability_zone`,`is_default`.
```
variable "availability_zone" {
default = "ap-guangzhou-3"
}
data "tencentcloud_vpc_subnets" "subnets" {
is_default        = true
availability_zone = var.availability_zone
}
output "default_subnet_id" {
value = data.tencentcloud_vpc_subnets.subnets.instance_list.0.subnet_id
}
output "default_vpc_id" {
value = data.tencentcloud_vpc_subnets.subnets.instance_list.0.vpc_id
}
```

data source support default vpc & subnet

---

CHANGELOG.md
tencentcloud/resource_tc_vpn_gateway.go

```
$ make testacc TESTARGS="-run=TestAccTencentCloudVpnGateway_basic"
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudVpnGateway_basic -timeout 120m
PASS
ok      github.com/terraform-providers/terraform-provider-tencentcloud/gendoc   2.599s [no tests to run]
=== RUN   TestAccTencentCloudVpnGateway_basic
--- PASS: TestAccTencentCloudVpnGateway_basic (122.43s)
PASS
ok      github.com/terraform-providers/terraform-provider-tencentcloud/tencentcloud     127.529s
```

FIX BUG: Resource: `tencentcloud_vpn_gateway` of postpaid charge type cannot be deleted normally

---

CHANGELOG.md
tencentcloud/data_source_tc_vpn_gateways.go
tencentcloud/resource_tc_ha_vip.go
tencentcloud/resource_tc_ha_vip_eip_attachment.go
tencentcloud/resource_tc_ha_vip_eip_attachment_test.go
tencentcloud/resource_tc_vpn_connection.go
tencentcloud/resource_tc_vpn_customer_gateway.go
tencentcloud/resource_tc_vpn_gateway.go
tencentcloud/service_tencentcloud_ssl.go
tencentcloud/service_tencentcloud_vpc.go
tencentcloud/validators.go

* Resource: `tencentcloud_vpn_gateway` add `InternalError` SDK error to triggering the retry process.
* Resource: `tencentcloud_vpn_gateway` fix read nil issue when the resource is not exist.
* Resource: `tencentcloud_clb_listener_rule` fix unclear error message of SSL type error.
* Resource: `tencentcloud_ha_vip_attachment` fix read nil issue when the resource is not exist.

Fix VPN read nil issue

---

tencentcloud/resource_tc_cam_group.go
tencentcloud/resource_tc_cam_group_membership.go
tencentcloud/resource_tc_cam_group_policy_attachment.go
tencentcloud/resource_tc_cam_policy.go
tencentcloud/resource_tc_cam_role.go
tencentcloud/resource_tc_cam_role_policy_attachment.go
tencentcloud/resource_tc_cam_saml_provider.go
tencentcloud/resource_tc_cam_user.go
tencentcloud/resource_tc_cam_user_policy_attachment.go
tencentcloud/service_tencentcloud_cam.go

make testacc TESTARGS="-run=TestAccTencentCloudCam"
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudCam -timeout 120m
PASS
ok      github.com/terraform-providers/terraform-provider-tencentcloud/gendoc  (cached) [no tests to run]
=== RUN   TestAccTencentCloudCamGroupMembershipsDataSource_basic
--- PASS: TestAccTencentCloudCamGroupMembershipsDataSource_basic (10.00s)
=== RUN   TestAccTencentCloudCamGroupPolicyAttachmentsDataSource_basic
--- PASS: TestAccTencentCloudCamGroupPolicyAttachmentsDataSource_basic (7.93s)
=== RUN   TestAccTencentCloudCamGroupsDataSource_basic
--- PASS: …

add time sleep to keep safe read

---

CHANGELOG.md
tencentcloud/resource_tc_kubernetes_as_scaling_group.go

bug fix : `tencentcloud_kubernetes_as_scaling_group` set a value to argument `key_ids` cause error

bug fix : `tencentcloud_kubernetes_as_scaling_group` set a value to argument `key_ids` cause error

---

tencentcloud/resource_tc_clb_attachment.go
tencentcloud/service_tencentcloud_clb.go

create:
`data.tencentcloud_instances.default: Refreshing state...
tencentcloud_clb_attachment.default[0]: Refreshing state... [id=#lbl-g84n3gr2#lb-1sp4y4so]
tencentcloud_clb_attachment.default[1]: Refreshing state... [id=#lbl-g84n3gr2#lb-1sp4y4so]
+ create
+ resource "tencentcloud_clb_attachment" "default" {
+ clb_id        = "lb-1sp4y4so"
+ id            = (known after apply)
+ listener_id   = "lbl-g84n3gr2"
+ protocol_type = (known after apply)
+ targets {
+ instance_id = "ins-fa2damgc"
+ port        = 80
+ weight      = 10
}
}
+ resource "tencentcloud_clb_attachment" "default" {
+ clb_id        = "lb-1sp4y4so"
+ id …

fix multi-attachment deletion issue

---

CHANGELOG.md
tencentcloud/resource_tc_cam_group_membership.go
tencentcloud/resource_tc_clb_attachment.go
tencentcloud/resource_tc_redis_instance.go
tencentcloud/service_tencentcloud_cam.go
website/docs/r/redis_instance.html.markdown

apply
```
$ terraform apply
2020/04/13 12:24:40 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
Use TF_LOG=TRACE to see Terraform's internal logs.
----
data.tencentcloud_instances.default: Refreshing state...
+ create
+ resource "tencentcloud_cam_group" "group_basic" {
+ create_time = (known after apply)
+ id          = (known after apply)
+ name        = "cam-group-membership-test"
+ remark      = "test"
}
+ resource "tencentcloud_cam_group_membership" "group_membership_basic" {
+ group_id = (known after apply)
+ id       = (known after apply)
+ user_ids = (known …
```

fix bugs when trying destroy multi-attachments resources

---

CHANGELOG.md
tencentcloud/connectivity/transport.go
tencentcloud/data_source_tc_redis_instances.go
tencentcloud/data_source_tc_redis_instances_test.go
tencentcloud/data_source_tc_redis_zone_config.go
tencentcloud/data_source_tc_redis_zone_config_test.go
tencentcloud/resource_tc_redis_backup_config_test.go
tencentcloud/resource_tc_redis_instance.go
tencentcloud/resource_tc_redis_instance_test.go
tencentcloud/service_tencentcloud_redis.go
website/docs/d/redis_instances.html.markdown
website/docs/d/redis_zone_config.html.markdown
website/docs/r/monitor_policy_group.html.markdown
website/docs/r/redis_instance.html.markdown

ENHANCEMENTS: 
Resource: `tencentcloud_redis_instance` add new argument `type_id`,`redis_shard_num`,`redis_replicas_num`
Data Source: `tencentcloud_redis_instances` add new argument  `type_id`,`redis_shard_num`,`redis_replicas_num`
Data Source: `tencentcloud_redis_zone_config` add output argument `type_id` and new output argument  `type_id`,`redis_shard_nums`,`redis_replicas_nums`
DEPRECATED:
* Resource: `tencentcloud_redis_instance`: optional argument `type` is no longer supported, replace by `type_id`.
* Data Source: `tencentcloud_redis_instances`: output argument `type` is no longer supported, replace by `type_id`
* Data Source: `tencentcloud_redis_zone_config`: output argument `type` is no longer supported, replace by `type_id` …

redis `type_id`,`redis_shard_num`,`redis_replicas_num` supports.

---

tencentcloud/resource_tc_cbs_storage.go
tencentcloud/resource_tc_cbs_storage_test.go

fix bug that changing pay type did not work and the basic case did not pass
```
$ make testacc TESTARGS=" -run=TestAccTencentCloudCbsStorage_upgrade"
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudCbsStorage_upgrade -timeout 120m
PASS
ok      github.com/terraform-providers/terraform-provider-tencentcloud/gendoc   (cached) [no tests to run]
=== RUN   TestAccTencentCloudCbsStorage_upgrade
=== PAUSE TestAccTencentCloudCbsStorage_upgrade
=== CONT  TestAccTencentCloudCbsStorage_upgrade
--- PASS: TestAccTencentCloudCbsStorage_upgrade (186.81s)
PASS
ok …
```

fix pass case

---

tencentcloud/resource_tc_gaap_http_domain.go

In case of some one-way https listener domains created in the past, the client certificate id is empty string and cannot be modified to "default".
The https listeners which use one-way authentication could not be modified to two-way authentication.
When the client certificate id is empty string,  `terraform plan` failed with following errors.
```
runtime error: index out of range [0] with length 0
2020-06-02T22:22:05.352+0900 [DEBUG] plugin.terraform-provider-tencentcloud_v1.35.0_x4: 
2020-06-02T22:22:05.352+0900 [DEBUG] plugin.terraform-provider-tencentcloud_v1.35.0_x4: goroutine 694 [running]:
2020-06-02T22:22:05.352+0900 [DEBUG] plugin.terraform-provider-tencentcloud_v1.35.0_x4: github.com/terraform-providers/terraform-provider-tencentcloud/tencentcloud.resourceTencentCloudGaapHttpDomai …
```

support when the client certificate id is empty

---

CHANGELOG.md
tencentcloud/connectivity/client.go
tencentcloud/resource_tc_instance.go

make testacc TESTARGS=" -run=TestAccTencentCloudEipAssociationWithInstance"
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudEipAssociationWithInstance -timeout 120m
PASS
ok      github.com/terraform-providers/terraform-provider-tencentcloud/gendoc   (cached) [no tests to run]
=== RUN   TestAccTencentCloudEipAssociationWithInstance
--- PASS: TestAccTencentCloudEipAssociationWithInstance (52.17s)
PASS
ok      github.com/terraform-providers/terraform-provider-tencentcloud/tencentcloud     52.190s

Fix cvm instance inconsistency when eip is attached to the cvm

---

tencentcloud/resource_tc_kubernetes_as_scaling_group.go

fix small logic issues.
***
$ make testacc TESTARGS=" -run=TestAccTencentCloudTkeAsResource"
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudTkeAsResource -timeout 120m
?   	github.com/terraform-providers/terraform-provider-tencentcloud	[no test files]
PASS
ok  	github.com/terraform-providers/terraform-provider-tencentcloud/gendoc	0.018s [no tests to run]
=== RUN   TestAccTencentCloudTkeAsResource
--- PASS: TestAccTencentCloudTkeAsResource (175.09s)
PASS
ok  	github.com/terraform-providers/terraform-provider-tencentcloud/tencentcloud	175.114s
?   	github.com/terraform-providers/terraform-provider-tencentcloud/tencentcloud/connectivity	[no test files]
? …

fix deal error for  kubernetes as group Read

---

CHANGELOG.md
tencentcloud/resource_tc_cos_bucket.go
tencentcloud/resource_tc_cos_bucket_test.go
tencentcloud/resource_tc_scf_function.go
tencentcloud/resource_tc_ssl_certificate.go
tencentcloud/service_tencentcloud_cos.go
website/docs/r/cos_bucket.html.markdown
website/docs/r/scf_function.html.markdown

make testacc TESTARGS=" -run=TestAccTencentCloudCos"
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudCos -timeout 120m
PASS
ok      github.com/terraform-providers/terraform-provider-tencentcloud/gendoc   0.016s [no tests to run]
=== RUN   TestAccTencentCloudCosBucketObjectDataSource
=== PAUSE TestAccTencentCloudCosBucketObjectDataSource
=== RUN   TestAccTencentCloudCosBucketDataSource_basic
=== PAUSE TestAccTencentCloudCosBucketDataSource_basic
=== RUN   TestAccTencentCloudCosBucketDataSource_tags
--- PASS: TestAccTencentCloudCosBucketDataSource_tags (24.94s)
=== RUN …

cos bucket support encryption and versioning

---

tencentcloud/resource_tc_gaap_http_domain.go

In some cases, `httpDomain.PolyClientCertificateAliasInfo` was not nil but empty list and `terraform plan` failed.
fixed this bug.

fix a condition for setting client certificate ids

---

tencentcloud/common.go
tencentcloud/resource_tc_instance.go

When cvm created success, its tags may not attached at once, since it's async.
We use a dedicated [tag](https://cloud.tencent.com/document/api/651/35326) api to attach and makes its behavior like a sync one.

fix cvm creation while its tags not sync issue

---

tencentcloud/resource_tc_cdn_domain.go
website/docs/r/cdn_domain.html.markdown

fix cdn resource fields description `doamin` --> `domain`.

fix cdn resource fields description

---

tencentcloud/data_source_tc_mysql_instance.go
tencentcloud/resource_tc_mysql_instance.go
website/docs/d/mysql_instance.html.markdown
website/docs/r/mysql_instance.html.markdown
website/docs/r/mysql_readonly_instance.html.markdown

fix description

---

CHANGELOG.md
tencentcloud/internal/helper/transform.go
tencentcloud/resource_tc_cam_role.go
tencentcloud/resource_tc_kubernetes_cluster_attachment.go
website/docs/r/cam_role.html.markdown
website/docs/r/kubernetes_cluster_attachment.html.markdown

With existing instances test case, the case need an exsting instance, therefor not put it into test file to make auto-tests.
```
make testacc TESTARGS=" -run=TestAccTencentCloudTkeAttachExistResource"
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudTkeAttachExistResource -timeout 120m
PASS
ok      github.com/terraform-providers/terraform-provider-tencentcloud/gendoc  (cached) [no tests to run]
=== RUN   TestAccTencentCloudTkeAttachExistResource
--- PASS: TestAccTencentCloudTkeAttachExistResource (336.47s)
PASS
ok      github.com/terraform-providers/terraform-provider-tencentcloud/tencentcloud     337.703s
? …
```

Add worker_config with resource `tencentcloud_kubernetes_cluster_attachment`

---

CHANGELOG.md
tencentcloud/data_source_tc_images.go
tencentcloud/data_source_tc_images_test.go
tencentcloud/service_tencentcloud_cbs.go
website/docs/d/images.html.markdown

$ make testacc TESTARGS=" -run=TestAccTencentCloudDataSourceImagesBase"
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudDataSourceImagesBase -timeout 120m
?   	github.com/terraform-providers/terraform-provider-tencentcloud	[no test files]
PASS
ok  	github.com/terraform-providers/terraform-provider-tencentcloud/gendoc	(cached) [no tests to run]
=== RUN   TestAccTencentCloudDataSourceImagesBase
--- PASS: TestAccTencentCloudDataSourceImagesBase (13.88s)
PASS
ok  	github.com/terraform-providers/terraform-provider-tencentcloud/tencentcloud	13.912s
?   	github.com/terraform-providers/terraform-provider-tencentcloud/tencentcloud/connectivity	[no test files]
? …

datasource images support snapshotSet

---

CHANGELOG.md
README.md

1. update readme for new repository

[update readme for new repository]

---

CHANGELOG.md
tencentcloud/resource_tc_gaap_http_rule.go
tencentcloud/resource_tc_gaap_http_rule_test.go
tencentcloud/service_tencentcloud_gaap.go
website/docs/r/gaap_http_rule.html.markdown

allow gaap http rule argument `realservers`  be Optional

feat: http rule realservers is optional

---

CHANGELOG.md
tencentcloud/data_source_tc_kubernetes_clusters.go
tencentcloud/service_tencentcloud_tke.go
website/docs/d/kubernetes_clusters.html.markdown

Data Source: `tencentcloud_kubernetes_clusters`add new arguments `cluster_as_enabled`,`node_name_type`,`cluster_extra_args`,`network_type`,`is_non_static_ip_mode`,`kube_proxy_mode`,`service_cidr`,`eni_subnet_ids`,`claim_expired_seconds` and
`deletion_protection`.

 Data Source: `tencentcloud_kubernetes_clusters`add new arguments.

---

CHANGELOG.md
tencentcloud/resource_tc_mongodb_instance.go
tencentcloud/resource_tc_mongodb_sharding_instance.go
tencentcloud/resource_tc_mongodb_standby_instance.go

1. remove spec update validation for mongodb instance in case SDK
changes its limitation without notifying us, so it's a protection.

[remove spec update validation]

---

CHANGELOG.md
tencentcloud/resource_tc_vpn_connection.go

The SDK will return this parameter reordered and cause an updating issue. And this parameter should not be set with type List.
terraform apply
```
terraform apply
2020/08/27 19:45:55 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
Use TF_LOG=TRACE to see Terraform's internal logs.
----
data.tencentcloud_vpc_instances.foo: Refreshing state...
+ create
+ resource "tencentcloud_vpn_connection" "connection" {
+ create_time                = (known after apply)
+ customer_gateway_id        = (known after apply)
+ encrypt_proto              = (known after apply)
+ id …
```

fix update issue in resource `tencentcloud_vpn_connection`

---

CHANGELOG.md
examples/tencentcloud-vpc/main.tf
tencentcloud/resource_tc_vpc_acl_attachment.go
tencentcloud/resource_tc_vpc_acl_attachment_test.go
website/docs/r/vpc_acl_attachment.html.markdown

change field `subnet_ids` to `subnet_id`.
***
± make testacc TESTARGS=" -run=TestAccTencentCloudVpcAclAttachment_basic"                                                                                                                                                                 ⏎
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudVpcAclAttachment_basic -timeout 120m
PASS
ok      github.com/terraform-providers/terraform-provider-tencentcloud/gendoc   0.016s [no tests to run]
=== RUN   TestAccTencentCloudVpcAclAttachment_basic
--- PASS: TestAccTencentCloudVpcAclAttachment_basic (8.35s)
PASS
ok …

acl attachment perfect example field

---

CHANGELOG.md
tencentcloud/extension_mongodb.go
tencentcloud/resource_tc_mongodb_instance.go
tencentcloud/resource_tc_mongodb_sharding_instance.go
tencentcloud/resource_tc_mongodb_standby_instance.go
website/docs/r/mongodb_instance.html.markdown
website/docs/r/mongodb_sharding_instance.html.markdown
website/docs/r/mongodb_standby_instance.html.markdown

1. ignore project tag
-----------

[fit to project tag]

---

CHANGELOG.md
tencentcloud/resource_tc_mongodb_instance.go
tencentcloud/resource_tc_mongodb_sharding_instance.go
tencentcloud/resource_tc_mongodb_standby_instance.go
tencentcloud/service_tencentcloud_mongodb.go

tencentcloud_mongodb_sharding_instance.mongodb_postpaid-sharding-keep: Destruction complete after 1m16s
tencentcloud_security_group.foo: Destroying... [id=sg-bnzg8an9]
tencentcloud_subnet.foo: Destroying... [id=subnet-lvj0mqwg]
tencentcloud_security_group.foo: Destruction complete after 1s
tencentcloud_subnet.foo: Destruction complete after 2s
tencentcloud_vpc.foo: Destroying... [id=vpc-b5zhxz0j]
tencentcloud_vpc.foo: Destruction complete after 2s
Destroy complete! Resources: 4 destroyed.

modify mongodb force_delete

---

CHANGELOG.md
tencentcloud/resource_tc_instance.go
tencentcloud/resource_tc_instance_test.go
tencentcloud/resource_tc_redis_instance.go
tencentcloud/service_tencentcloud_cvm.go

make testacc TESTARGS=" -run=TestAccTencentCloudInstanceWithKeyPair"
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudInstanceWithKeyPair -timeout 120m
PASS
=== RUN   TestAccTencentCloudInstanceWithKeyPair
=== PAUSE TestAccTencentCloudInstanceWithKeyPair
=== CONT  TestAccTencentCloudInstanceWithKeyPair
--- PASS: TestAccTencentCloudInstanceWithKeyPair (126.81s)
PASS
ok      github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud       126.833s

Fix cvm key_name update error

---

tencentcloud/data_source_tc_redis_instances.go
tencentcloud/resource_tc_kubernetes_cluster.go
tencentcloud/resource_tc_redis_instance.go

for reasons:
- in some environments, the zone name doesn't respect this rule
- not all resources apply this rule, results a inconsistent codebase
- if region/zone not matched, the proper upstream server will panic

remove zone string contains region name checks

---

CHANGELOG.md
tencentcloud/resource_tc_mysql_instance.go

```
$ terraform apply
2020/10/16 19:10:41 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
Use TF_LOG=TRACE to see Terraform's internal logs.
----
+ create
+ resource "tencentcloud_mysql_instance" "prepaid" {
+ auto_renew_flag   = 1
+ availability_zone = "ap-guangzhou-3"
+ charge_type       = "PREPAID"
+ engine_version    = "5.7"
+ first_slave_zone  = "ap-guangzhou-3"
+ force_delete      = false
+ gtid              = (known after apply)
+ id                = (known after apply)
+ instance_name     = "testAccMysqlPrepaid"
+ internet_host     = (known after apply)
+ …
```

fix create prepaid mysql error

---

CHANGELOG.md
examples/tencentcloud-clb/main.tf
tencentcloud/basic_test.go
tencentcloud/data_source_tc_availability_regions.go
tencentcloud/data_source_tc_clb_attachments.go
tencentcloud/data_source_tc_clb_listener_rules.go
tencentcloud/data_source_tc_clb_listener_rules_test.go
tencentcloud/data_source_tc_clb_listeners.go
tencentcloud/data_source_tc_clb_listeners_test.go
tencentcloud/data_source_tc_clb_redirections.go
tencentcloud/data_source_tc_instance_types.go
tencentcloud/data_source_tc_instance_types_test.go
tencentcloud/extension_cvm.go
tencentcloud/resource_tc_cdn_domain.go
tencentcloud/resource_tc_clb_attachment.go
tencentcloud/resource_tc_clb_listener.go
tencentcloud/resource_tc_clb_listener_rule.go
tencentcloud/resource_tc_clb_listener_rule_test.go
tencentcloud/resource_tc_clb_listener_test.go
tencentcloud/resource_tc_clb_redirection.go
tencentcloud/resource_tc_clb_target_group_attachment.go
tencentcloud/service_tencentcloud_clb.go
tencentcloud/service_tencentcloud_cvm.go
website/docs/d/availability_regions.html.markdown
website/docs/d/instance_types.html.markdown
website/docs/r/cdn_domain.html.markdown
website/docs/r/clb_listener.html.markdown
website/docs/r/clb_listener_rule.html.markdown

CLB 
```
$ make testacc TESTARGS=" -run=TestAccTencentCloudClbListener"
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudClbListener -timeout 120m
PASS
=== RUN   TestAccTencentCloudClbListenerRulesDataSource
=== PAUSE TestAccTencentCloudClbListenerRulesDataSource
=== RUN   TestAccTencentCloudClbListenersDataSource
=== PAUSE TestAccTencentCloudClbListenersDataSource
=== RUN   TestAccTencentCloudClbListenerRule_basic
=== PAUSE TestAccTencentCloudClbListenerRule_basic
=== RUN …
```

CLB support import

---

CHANGELOG.md
tencentcloud/resource_tc_clb_listener.go
tencentcloud/resource_tc_clb_listener_test.go
tencentcloud/resource_tc_clb_target_group_attachment.go
tencentcloud/resource_tc_clb_target_group_attachment_test.go
tencentcloud/service_tencentcloud_clb.go
website/docs/r/clb_listener.html.markdown
website/docs/r/clb_target_group_attachment.html.markdown

make testacc TESTARGS="-run TestAccTencentClbTargetGroupAttachmentHttpResource"
TF_ACC=1 go test ./... -v -run TestAccTencentClbTargetGroupAttachmentHttpResource -timeout 120m
PASS
=== RUN   TestAccTencentClbTargetGroupAttachmentHttpResource
--- PASS: TestAccTencentClbTargetGroupAttachmentHttpResource (45.21s)
PASS
ok      github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud       46.752s
?       github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/connectivity …

add tcp/udp listener target group attachment

---

tencentcloud/extension_mongodb.go
tencentcloud/resource_tc_mongodb_standby_instance.go
website/docs/r/mongodb_instance.html.markdown
website/docs/r/mongodb_sharding_instance.html.markdown
website/docs/r/mongodb_standby_instance.html.markdown

1. optimize document for mongodb

[optimize document]

---

tencentcloud/provider.go
tencentcloud/resource_tc_kubernetes_as_scaling_group.go
tencentcloud/resource_tc_kubernetes_cluster.go
website/docs/d/kubernetes_clusters.html.markdown
website/docs/r/kubernetes_as_scaling_group.html.markdown
website/docs/r/kubernetes_cluster.html.markdown
website/docs/r/kubernetes_cluster_attachment.html.markdown
website/docs/r/kubernetes_scale_worker.html.markdown
website/tencentcloud.erb

optimize document

---

CHANGELOG.md
tencentcloud/extension_cvm.go
tencentcloud/resource_tc_instance.go

```
terraform apply
+ create
+ resource "tencentcloud_instance" "foo" {
+ allocate_public_ip                      = false
+ availability_zone                       = "ap-shanghai-3"
+ create_time                             = (known after apply)
+ disable_monitor_service                 = true
+ disable_security_service                = false
+ expired_time                            = (known after apply)
+ force_delete                            = false
+ id                                      = (known after apply)
+ image_id                                = "img-25szkc8t"
+ instance_charge_type                    = …
```

 fix bug that waiting 5 minutes when cloud disk sold out

---

CHANGELOG.md
tencentcloud/data_source_tc_tcr_vpc_attachments.go
tencentcloud/extension_tcr.go
tencentcloud/resource_tc_tcr_vpc_attachment.go
tencentcloud/service_tencentcloud_tcr.go
website/docs/d/tcr_vpc_attachments.html.markdown
website/docs/r/tcr_vpc_attachment.html.markdown

```
terraform apply
Warning: Provider development overrides are in effect
The following provider development overrides are set in the CLI configuration:
- hashicorp/tencentcloud in /home/hxt/projects/terraform-provider-tencentcloud
The behavior may therefore not match any released version of the provider and
applying changes may cause the state to become incompatible with published
releases.
+ create
<= read (data resources)
<= data "tencentcloud_tcr_vpc_attachments" "example"  {
+ id                  = (known after apply)
+ instance_id         = (known after apply)
+ vpc_attachment_list = (known after apply)
}
+ resource …
```

add tcr vpc dns

---

CHANGELOG.md
tencentcloud/data_source_tc_ssl_certificates.go
tencentcloud/resource_tc_ssl_certificate.go
tencentcloud/resource_tc_ssl_certificate_test.go
tencentcloud/service_tencent_ssl_certificate.go
tencentcloud/service_tencentcloud_clb.go
tencentcloud/service_tencentcloud_ssl.go
website/docs/r/ssl_certificate.html.markdown

```
TF_ACC=1 go test ./... -v -run=TestAccTencentCloudSslCertificate_basic -timeout 120m
?   	github.com/tencentcloudstack/terraform-provider-tencentcloud	[no test files]
PASS
ok  	github.com/tencentcloudstack/terraform-provider-tencentcloud/gendoc	0.042s [no tests to run]
=== RUN   TestAccTencentCloudSslCertificate_basic
--- PASS: TestAccTencentCloudSslCertificate_basic (2.66s)
PASS
ok  	github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud	2.676s
?   	github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/connectivity	[no test files]
?   	github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/internal/helper	[no test files]
? …
```

resource tencentcloud_ssl_certificate fix bug when destroy a certificate

---

CHANGELOG.md
tencentcloud/resource_tc_kubernetes_cluster.go
tencentcloud/service_tencentcloud_tke.go
website/docs/r/kubernetes_cluster.html.markdown

```
terraform apply
Warning: Provider development overrides are in effect
The following provider development overrides are set in the CLI configuration:
- hashicorp/tencentcloud in /home/hxt/projects/terraform-provider-tencentcloud
- tencentcloudstack/tencentcloud in /home/hxt/projects/terraform-provider-tencentcloud
The behavior may therefore not match any released version of the provider and
applying changes may cause the state to become incompatible with published
releases.
+ create
+ resource "tencentcloud_kubernetes_cluster" "managed_cluster" {
+ certification_authority                    = (known after apply)
+ …
```

add tke node_pool_global_config

---

CHANGELOG.md
tencentcloud/resource_tc_kubernetes_cluster.go
tencentcloud/service_tencentcloud_tke.go
website/docs/r/kubernetes_cluster.html.markdown

- add `RuntimeVersion` param for tke cluster resource
- update CHANGELOG.md

feat: tke instance creation - add RuntimeVersion param

---

tencentcloud/basic_test.go
tencentcloud/provider.go
tencentcloud/resource_tc_monitor_tmp_tke_template_attachment.go
tencentcloud/resource_tc_monitor_tmp_tke_template_attachment_test.go
tencentcloud/service_tencentcloud_tke.go
website/docs/r/monitor_tmp_tke_template_attachment.html.markdown
website/tencentcloud.erb

add resource SyncPrometheusTemp

add resource template attachment

---

tencentcloud/resource_tc_monitor_tmp_exporter_integration.go
tencentcloud/resource_tc_monitor_tmp_tke_alert_policy.go
tencentcloud/resource_tc_monitor_tmp_tke_cluster_agent.go
tencentcloud/resource_tc_monitor_tmp_tke_config.go
tencentcloud/resource_tc_monitor_tmp_tke_global_notification.go
tencentcloud/resource_tc_monitor_tmp_tke_record_rule_yaml.go
tencentcloud/resource_tc_monitor_tmp_tke_template.go
tencentcloud/resource_tc_monitor_tmp_tke_template_attachment.go
website/docs/r/monitor_tmp_exporter_integration.html.markdown
website/docs/r/monitor_tmp_tke_alert_policy.html.markdown
website/docs/r/monitor_tmp_tke_cluster_agent.html.markdown
website/docs/r/monitor_tmp_tke_config.html.markdown
website/docs/r/monitor_tmp_tke_global_notification.html.markdown
website/docs/r/monitor_tmp_tke_record_rule_yaml.html.markdown
website/docs/r/monitor_tmp_tke_template.html.markdown
website/docs/r/monitor_tmp_tke_template_attachment.html.markdown

docs: add example

---

tencentcloud/resource_tc_monitor_tmp_cvm_agent.go
website/docs/r/monitor_tmp_cvm_agent.html.markdown

fix: add agent_id

---

tencentcloud/resource_tc_kubernetes_cluster.go

[fix ](fix: tke cluster para valiate error message)

fix: tke cluster para valiate error message

---

tencentcloud/data_source_tc_dbbrain_security_audit_log_export_tasks.go
tencentcloud/data_source_tc_dbbrain_security_audit_log_export_tasks_test.go
tencentcloud/data_source_tc_dbbrain_sql_filters.go
tencentcloud/data_source_tc_dbbrain_sql_filters_test.go
tencentcloud/provider.go
tencentcloud/resource_tc_dbbrain_security_audit_log_export_task.go
tencentcloud/resource_tc_dbbrain_security_audit_log_export_task_test.go
tencentcloud/resource_tc_dbbrain_sql_filter.go
tencentcloud/service_tencentcloud_dbbrain.go
website/docs/d/dbbrain_security_audit_log_export_tasks.html.markdown
website/docs/d/dbbrain_sql_filters.html.markdown
website/docs/r/dbbrain_security_audit_log_export_task.html.markdown
website/docs/r/dbbrain_sql_filter.html.markdown
website/tencentcloud.erb

Data Source
tencentcloud_dbbrain_sql_filters
tencentcloud_dbbrain_security_audit_log_export_tasks

feat:support dbbrain datasource

---

tencentcloud/resource_tc_pts_cron_job.go
tencentcloud/resource_tc_pts_cron_job_test.go
website/docs/r/pts_cron_job.html.markdown

fix: modify cron unit

---

tencentcloud/resource_tc_monitor_tmp_alert_rule_test.go

fix: modify monitor unit

---

tencentcloud/resource_tc_tem_application_service.go
tencentcloud/resource_tc_tem_environment.go
website/docs/r/tem_application_service.html.markdown

fix: modify tag

---

tencentcloud/resource_tc_monitor_tmp_tke_alert_policy.go
tencentcloud/resource_tc_monitor_tmp_tke_global_notification.go
website/docs/r/monitor_tmp_tke_alert_policy.html.markdown
website/docs/r/monitor_tmp_tke_global_notification.html.markdown

fix: modify example

---

.changelog/1527.txt
tencentcloud/resource_tc_tem_application.go
website/docs/r/tem_application.html.markdown

The `description` parameter is required even on the `CreateApplication` API spec: https://www.tencentcloud.com/document/product/1094/42036
And in fact trying to apply without that causes an error.

Make the `description` parameter of the TEM Application required

---

tencentcloud/resource_tc_cdn_domain.go
website/docs/r/cdn_domain.html.markdown

fix: modify doc

---

.changelog/1546.txt
tencentcloud/service_tencentcloud_tke.go

fix: tke cluster endpoint CheckOneOfClusterNodeReady include serverless nodes

fix: tke cluster endpoint can be created even if cluster only have serverless node

---

tencentcloud/resource_tc_teo_rule_engine_test.go
tencentcloud/resource_tc_teo_zone_test.go
tencentcloud/service_tencentcloud_teo.go

fix: modify teo unit

---

tencentcloud/basic_test.go
tencentcloud/data_source_tc_tsf_pod_instances_test.go
tencentcloud/resource_tc_redis_ssl_test.go
tencentcloud/resource_tc_redis_switch_master_test.go
tencentcloud/resource_tc_tse_cngw_route_rate_limit_test.go
tencentcloud/resource_tc_tse_cngw_service_rate_limit_test.go
tencentcloud/resource_tc_tsf_deploy_container_group_test.go
tencentcloud/resource_tc_tsf_operate_container_group_test.go

fix: tsf redis test

---

.changelog/2090.txt
tencentcloud/resource_tc_kubernetes_cluster.go

1. Background: When using the default value of docker_graph_path, there is a situation where the parameter is not passed to the cloud API. The default value of the cloud API is /var/lib/contained, which causes the resource created by Terraform to not meet the requirements.
2. Bug: DiffSuppressFunc ignores the default value of docker_graph_path when calculating differences.
The modification should only affect incremental changes and not impact existing data.
3. The modification should only affect incremental changes and not impact existing data.

fix DiffSuppressFunc would ignore docker_graph_path defaults when computing diffs

---

tencentcloud/resource_tc_as_scaling_config.go
tencentcloud/resource_tc_kubernetes_as_scaling_group.go
tencentcloud/resource_tc_kubernetes_node_pool.go
website/docs/r/as_scaling_config.html.markdown
website/docs/r/kubernetes_node_pool.html.markdown

update as and tke docs

---

website/docs/r/kubernetes_node_pool.html.markdown
website/docs/r/kubernetes_scale_worker.html.markdown

update the doc for duplicated `data_disk` field

---

tencentcloud/resource_tc_kubernetes_addon_attachment_test.go
tencentcloud/resource_tc_kubernetes_backup_storage_location_test.go
tencentcloud/resource_tc_kubernetes_cluster_endpoint_test.go
tencentcloud/resource_tc_kubernetes_node_pool_test.go

TestAccTencentCloudKubernetesAddonAttachmentResource: e2e sweeper有瑕疵，存在脏数据，code fix
TestAccTencentCloudKubernetesBackupStorageLocationResource_Basic：1.e2e sweeper有问题，无法删除备份仓库，code fix; 2.缺少对应的CAM权限。
TestAccTencentCloudKubernetesClusterEndpointResource：字段更新， 需要同步调整e2e用例，code fix
TestAccTencentCloudKubernetesNodePoolResource_GPUInstance：sweeper没有清理gpu相关asg，导致asg没有释放

feat:adjust e2e sweeper

---

.changelog/2170.txt
tencentcloud/resource_tc_kubernetes_node_pool.go

1、fix bug in node pool creation

fix bug in node pool creation

---

CHANGELOG.md

add changelog of release version v1.81.33

docs: add changelog of release version v1.81.33

---

.changelog/2177.txt
tencentcloud/provider.go
tencentcloud/resource_tc_cam_user_permission_boundary_attachment.go
tencentcloud/resource_tc_cam_user_permission_boundary_attachment_test.go
tencentcloud/service_tencentcloud_cam.go
website/docs/r/cam_user_permission_boundary_attachment.html.markdown
website/tencentcloud.erb

add resource cam permission boundary

feat: cam permission boundary

---

CHANGELOG.md

add changelog of release version v1.81.34

docs: add changelog of release version v1.81.34

---

.changelog/2192.txt
tencentcloud/provider.go
tencentcloud/resource_tc_mps_event.go
tencentcloud/resource_tc_mps_event_test.go
tencentcloud/resource_tc_mps_flow.go
tencentcloud/resource_tc_mps_flow_test.go
tencentcloud/resource_tc_mps_start_flow_operation.go
tencentcloud/resource_tc_mps_start_flow_operation_test.go
tencentcloud/service_tencentcloud_mps.go
website/docs/r/mps_event.html.markdown
website/docs/r/mps_flow.html.markdown
website/tencentcloud.erb

tencentcloud_mps_flow
tencentcloud_mps_event
tencentcloud_mps_start_flow_operation（文档暂不暴露）

support mps flow resource

---

CHANGELOG.md

add changelog of version v1.81.36

docs: add changelog of version v1.81.36

---

CHANGELOG.md

add changelog of version 1.81.38

docs: add changelog of version 1.81.38

---

CHANGELOG.md

add change log of version v1.81.39

docs: add change log of version v1.81.39

---

.github/workflows/fmt.yml
.github/workflows/golangci-lint.yml
.golangci.yml

update golang-ci parallel parameter

ci: update golang-ci parallel parameter

---

CHANGELOG.md

add changelog of version v1.81.44

docs: add changelog of version v1.81.44

---

CHANGELOG.md

add changelog of version v1.81.47

docs: add changelog of version v1.81.47

---

CHANGELOG.md

add changelog of version v1.81.49

docs: add changelog of version v1.81.49

---

.changelog/2454.txt
tencentcloud/provider.md
tencentcloud/services/clb/resource_tc_clb_target_group_attachments.go
tencentcloud/services/clb/resource_tc_clb_target_group_attachments.md
tencentcloud/services/clb/resource_tc_clb_target_group_attachments_test.go
tencentcloud/services/clb/service_tencentcloud_clb.go
website/docs/r/clb_target_group_attachments.html.markdown
website/tencentcloud.erb

Support two-way binding of clb and targetGroup

feat: support target attach clb

---

tencentcloud/services/vpc/resource_tc_vpc_acl.go
tencentcloud/services/vpc/service_tencentcloud_vpc.go
website/docs/r/vpc_acl.html.markdown

doc: port fmt

---

.changelog/2497.txt
tencentcloud/services/clb/extension_clb.go
tencentcloud/services/clb/resource_tc_clb_attachment.go

When clb is bound to the backend, cross-domain writing to the `target` is not supported.

fix: nat refresh

---

.changelog/2489.txt
go.mod
go.sum
tencentcloud/services/clb/resource_tc_clb_target_group_attachments.go
tencentcloud/services/clb/resource_tc_clb_target_group_attachments_test.go
tencentcloud/services/clb/service_tencentcloud_clb.go
vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
vendor/modules.txt
website/docs/r/clb_target_group_attachments.html.markdown

1、add ForceNew
2、Fix empty parameters

fix(clb): [116078526]Support four-layer lb

---

.changelog/2545.txt
go.mod
go.sum
tencentcloud/services/cls/resource_tc_cls_topic.go
tencentcloud/services/cls/resource_tc_cls_topic.md
tencentcloud/services/cls/resource_tc_cls_topic_test.go
vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cls/v20201016/client.go
vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cls/v20201016/errors.go
vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cls/v20201016/models.go
vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/json/encode.go
vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/oidc_role_arn_provider.go
vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/role_arn_credential.go
vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tag/v20180813/client.go
vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tag/v20180813/errors.go
vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tag/v20180813/models.go
vendor/modules.txt
website/docs/r/cls_topic.html.markdown

fix(cls): [116280037]support hot_period, describes params

---

.changelog/2555.txt
tencentcloud/services/privatedns/resource_tc_private_dns_zone.go
website/docs/r/private_dns_zone.html.markdown

fix(private_dns): [116458440] Add ForceNew attribute to domain parameter

---

.changelog/2556.txt
tencentcloud/services/apigateway/resource_tc_api_gateway_api_key_attachment.md
website/docs/r/api_gateway_api_key_attachment.html.markdown

fix(apigw): [116458787] Remove private information from documents 

---

.changelog/2564.txt
tencentcloud/provider.md
tencentcloud/services/bh/resource_tc_dasb_acl.go
tencentcloud/services/bh/resource_tc_dasb_bind_device_account_password.md
tencentcloud/services/bh/resource_tc_dasb_bind_device_account_private_key.md
tencentcloud/services/bh/resource_tc_dasb_bind_device_resource.md
tencentcloud/services/bh/resource_tc_dasb_device.go
tencentcloud/services/bh/resource_tc_dasb_device_account.go
tencentcloud/services/bh/resource_tc_dasb_device_account.md
tencentcloud/services/bh/resource_tc_dasb_device_group_members.go
tencentcloud/services/bh/resource_tc_dasb_device_group_members.md
tencentcloud/services/bh/resource_tc_dasb_resource.go
tencentcloud/services/bh/resource_tc_dasb_resource.md
tencentcloud/services/bh/resource_tc_dasb_user.go
tencentcloud/services/bh/resource_tc_dasb_user_group.md
tencentcloud/services/bh/resource_tc_dasb_user_group_members.go
tencentcloud/services/bh/resource_tc_dasb_user_group_members.md
tencentcloud/services/bh/service_tencentcloud_dasb.go
website/docs/r/dasb_bind_device_account_password.html.markdown
website/docs/r/dasb_bind_device_account_private_key.html.markdown
website/docs/r/dasb_bind_device_resource.html.markdown
website/docs/r/dasb_device_account.html.markdown
website/docs/r/dasb_device_group_members.html.markdown
website/docs/r/dasb_resource.html.markdown
website/docs/r/dasb_user_group.html.markdown
website/docs/r/dasb_user_group_members.html.markdown
website/tencentcloud.erb

fix(bh): [116555803] Fix errors in querying user group members

---

.changelog/2593.txt
tencentcloud/services/tcr/resource_tc_tcr_instance.go
tencentcloud/services/tcr/resource_tc_tcr_instance_test.go
website/docs/r/tcr_instance.html.markdown

feat(tcr): [116375010]support parma regionName

---

.changelog/2601.txt
tencentcloud/services/vpc/resource_tc_security_group_lite_rule.go
tencentcloud/services/vpc/resource_tc_security_group_lite_rule.md
website/docs/r/security_group_lite_rule.html.markdown

deprecated: tencentcloud_security_group_lite_rule

docs(clb): [116790844]Waste resources

---

.changelog/2622.txt
tencentcloud/services/clb/resource_tc_clb_attachment.md
website/docs/r/clb_attachment.html.markdown

docs(clb): [116968016]update-doc

---

.changelog/2653.txt
tencentcloud/services/cls/resource_tc_cls_alarm.go
tencentcloud/services/cls/resource_tc_cls_alarm.md
tencentcloud/services/cls/resource_tc_cls_alarm_test.go
website/docs/r/cls_alarm.html.markdown

fix(cls): [117616412] support `alarm_level` params

---

.changelog/2656.txt
tencentcloud/provider.md
website/docs/r/organization_org_manage_policy.html.markdown
website/docs/r/organization_org_manage_policy_config.html.markdown
website/docs/r/organization_org_manage_policy_target.html.markdown
website/tencentcloud.erb

Supplementary documentation：
`tencentcloud_organization_org_manage_policy 
tencentcloud_organization_org_manage_policy_config 
tencentcloud_organization_org_manage_policy_target `

docs(tco): [117662850]fix doc

---

.changelog/2618.txt
tencentcloud/services/postgresql/resource_tc_postgresql_instance.go
tencentcloud/services/postgresql/resource_tc_postgresql_instance.md
tencentcloud/services/postgresql/resource_tc_postgresql_instance_test.go
website/docs/r/postgresql_instance.html.markdown

fix(postgresql): [117252443] support params `db_major_version` create resource

---

.changelog/2671.txt
tencentcloud/services/cam/data_source_tc_user_info.go
tencentcloud/services/cam/data_source_tc_user_info_test.go

feat(cam): [117618077]support retry

---

.changelog/2784.txt
tencentcloud/services/cvm/resource_tc_instance.go

Reverts tencentcloudstack/terraform-provider-tencentcloud#2784

Revert "fix(cvm): [116173103] update destroy function"

---

tencentcloud/services/postgresql/resource_tc_postgresql_instance.go

fix yunti build:
tencentcloud_postgresql_instance

fix(pgsql): [119760660] fix yunti 

---

.changelog/2918.txt
go.mod
go.sum
tencentcloud/services/tke/resource_tc_kubernetes_cluster.go
tencentcloud/services/tke/resource_tc_kubernetes_cluster_extension.go
vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525/client.go
vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525/models.go
vendor/modules.txt
website/docs/r/kubernetes_cluster.html.markdown

feat(tke): [120409794] support `cluster_os ` field to update and adjust its set logic

---

tencentcloud/services/cvm/resource_tc_cvm_launch_template.go

Initially noticed this problem when I tried to create a launch template containing the following block:
```
internet_accessible {
public_ip_assigned = true
internet_max_bandwidth_out = 100
}
```
This resulted in an error during apply like this:
```
Code=InvalidParameterValue, Message=The value `` specified in the parameter `.InternetAccessible.InternetChargeType` is invalid.
```
I figured okay, I'll just add what should be the defaults and get on with it. But ultimately I got the same error from the `BandwidthPackageId` field. There is no good default value for it, so I was unable to make the launch template.
Turns out that throughout the SDK, all scalar fields are always included, at least wherever `InterfacesHeadMap` is used. The value of the individual fields is never checked, so every …

fix(cvm): Fix optional parameters never being omitted from requests
